### ISSUE TITLE
Allowed HTML tags does not work, also image popup do not work

### ISSUE THREAD

**Issue by Mohika** [GavickPro/News-Show-Pro-GK5#100]
Hi there .. I really need this ... it clearly states in your module that I can allow certain html tags to be allowed while "Clean HTML code in the text" is on ... it simply does not work ...  it strips all tags ... 

Also there is clear statement that I can popup an image if the image link is on  but it does not work either .. 

Why .. ?

Tags I tryed are span,p,h3 ... and yes I have latest GK5 and its on joomla 3.1.5

**Comment by mohamedsai** [comment]
very useful tags.
<a href="http://www.watania.net">watania.net</a>
