### ISSUE TITLE
Error: No articles to display NSP5 + EB 

### ISSUE THREAD

**Issue by thodorisgo** [GavickPro/News-Show-Pro-GK5#224]
As mentioned on Gavick forum suddenly the module stopped collecting the easyblog articles and shows me this error "Error: No articles to display".

I use the module to display last months most readed articles so i had the "Show articles created in the last X days" setted up to 30. If i remove this value it displays me the articles but for a weird reason it stopped showing the articles i posted within those 30 days.

**Comment by martinwhyte** [comment]
hello,

After installing News Show Pro GK5, i outputs "Error: No articles to display" i've set the offset starting ranging from -12 to +12 and still the same error. im trying to use it for Easy Blog. But i noticed when i run the site on XAMPP on my local host, News Show Pro GK5 works fine but once i upload it on a live server, it reads "Error: No articles to display"! pls how do i sort this out?
