### ISSUE TITLE
Links in news don't open in correct page

### ISSUE THREAD

**Issue by mlaguia** [GavickPro/News-Show-Pro-GK5#246]
Hi,
I have installed News Show Pro GK5 in a joomal 2.5 installation. The url is: http://www.admarina.com
At the bottom of the page is the NSP GK5 module...

I have a problem with the links, when you click on them in the module, the article is opened at the bottom of the homepage. Curiously, when you click again in the the same or in any other link of the module, then it opens in the correct page.

How can I solve this?
Thanks

**Comment by dziudek** [comment]
Hello,

Please check if the category where are displayed the problematic links has a proper menu item.

**Comment by mlaguia** [comment]
Hi Tomasz, I cheked the category and it have a unique alias name.

Which can be the problem?

Thanks
Marc.

2015-01-09 8:15 GMT+01:00 Tomasz Dziuda <notifications@github.com>:

> Hello,
>
> Please check if the category where are displayed the problematic links has
> a proper menu item.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GavickPro/News-Show-Pro-GK5/issues/246#issuecomment-69301278>
> .
>



-- 
Marc Laguia
650 802 592

**Comment by dziudek** [comment]
The category alias is not connected with your issue - you have to specify a menu item for a category.
