### ISSUE TITLE
Dynamic Data NSP GK5 

### ISSUE THREAD

**Issue by BNDragon** [GavickPro/News-Show-Pro-GK5#248]
Hi there,

I'm building a filter to my articles and I want to know if it is possible to make a NSP GK5 module with dynamic source.

I'm using seblod/Community builder and NSP GK5 in my website, and I need to make a filter to show articles of a user (ie).

It is possible to make some like gk5Source=authorID.articles.

I need it to categories too.

Thanks in advance.
BN

**Comment by dziudek** [comment]
Hello,

In this case you will have to implement a data source by yourself, because this is a custom work beyond of our technical support.

**Comment by BNDragon** [comment]
Hi dziudek,

Thanks for your reply,

I was afraid that you say that. 
I have no idea how to do it.

Thanks any way.
BN
