### ISSUE TITLE
subcategories showcase

### ISSUE THREAD

**Issue by alfredopacino** [GavickPro/News-Show-Pro-GK5#249]
Hi, there is a way to show the subcategories (not the articles) in this module? I'm using Grid news mode, I need to show the subcategories, not the articles.

best regards

**Comment by dziudek** [comment]
As I have replied in other issue - you have to select specific subcategories - please use a data source which uses categories - then you will get a list of all categories and subcategories to select.

**Comment by alfredopacino** [comment]
https://www.diigo.com/item/image/51ynl/oa0c
this is my setting
I get the articles in "Giochi" not the articles in the subcategories, nor the subcategories itself.

**Comment by dziudek** [comment]
Sorry but the module is designed for display the article items only, not categories as an items.
