### ISSUE TITLE
Change article header H class?

### ISSUE THREAD

**Issue by ckubs** [GavickPro/News-Show-Pro-GK5#250]
I use your module in a Joomla website to populate my homepage with latest articles from my categories.
Bumped in a SEO problem as by defaul GK5 NSP outputs article titles with H4 headers in all the templates and I want to have them H2 or atlast H3 headers.

Is there a way to change the H4 classes? I know I can edit the module templates buit I don't know if this is the best way because I'll probably lose the edits after the first update.

Thank you :)

**Comment by dziudek** [comment]
Hello,

With the newer version of the module (like 1.7 or 1.8) you can override the module templates in your template overrides - then you won't lose your changes after module update.

**Comment by ckubs** [comment]
@dziudek Thanks for the response. Good to know the future update will adress this :D

**Comment by dziudek** [comment]
@ckubs - the mentioned feature is currently available, because current version is 1.8 ;)
