### ISSUE TITLE
Permanent lock

### ISSUE THREAD

**Issue by Mr-Kostek** [GavickPro/News-Show-Pro-GK5#252]
Hi. I've purchased on www.gavick.com layotut "Creativity". It has module News Show Pro GK5. I have problem with this module. I'ts locked. I can go inside it but I can't change anything. When I click "Save" it goes out to main manu with other modules. I can't edit copy of this module either. I've tried unlock it from system/unlock. I've tried to change back-end layout from isi to hathor (I've read that thic can be a problem). Nothing works.
Servers on www.az.pl and it's ok, I have other pages on this server and it works fine.

My page: www.chill-out.com.pl

**Comment by dziudek** [comment]
Hello,

Did you tried to use a global check-in? 
http://www.joomlart.com/tutorials/joomla-tutorials/joomla-site-maintenance-global-check-in-explained

**Comment by Mr-Kostek** [comment]
Tak, odblokowanie robiłem zarówno w modułach jak i w menu system.
--
Wysłane z mojego telefonu za pomocą aplikacji myMail dla Androida.
środa, 21 stycznia 2015, 00:22AM +01:00 od Tomasz Dziuda <notifications@github.com>:
Hello,
Did you tried to use a global check-in?
http://www.joomlart.com/tutorials/joomla-tutorials/joomla-site-maintenance-global-check-in-explained

**Comment by dziudek** [comment]
Proszę w tej sytuacji wysłać mi na maila dziudek[at]gavick[dot]com dane dostępowe do strony.
