### ISSUE TITLE
Error News Show Pro GK5

### ISSUE THREAD

**Issue by user2305** [GavickPro/News-Show-Pro-GK5#253]
Hello. We had set News Show Pro GK5 in Joomla! 2.5. We launched a new version of Joomla! 3.3 After you install our module we had an error. How can I fix it? Thank you.

Error:

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 0,12' at line 21 SQL=SELECT content.id AS iid FROM ajbz4_content AS content WHERE content.state = 1 AND content.access IN (1,1,2,3,4) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-01-11 17:39:39' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-01-11 17:39:39' ) ORDER BY content. DESC LIMIT 0,12;

**Comment by dziudek** [comment]
Hello, 
Did you installed a module in version for J!3.x?
Please resave the module settings and please specify the order option in the data source tab again.

**Comment by user2305** [comment]
Hello. Removed for 2.5 and installed for 3.3.

**Comment by user2305** [comment]
I badly understand English. Sorry

**Comment by dziudek** [comment]
And the problem still appears? Did you tried to resave the module settings?

**Comment by user2305** [comment]
Added position, saved the settings and the home page came out error.

http://xn--80asbmbdpjgd4h.xn--p1ai/images/NEPOSEDA/34334.jpg

http://xn--80asbmbdpjgd4h.xn--p1ai/images/NEPOSEDA/34343.jpg

**Comment by user2305** [comment]
Try again to remove the module and install?

**Comment by user2305** [comment]
install mod_news_pro_gk4_J!3.zip. 
Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'content.id = 14615 OR content.id = 14614 OR content.id = 14605 OR content.id ' at line 27 SQL=SELECT categories.title AS cat, content.id AS ID, content.access AS access, categories.title AS cat, users.email AS author_email, users.name AS author, content_rating.rating_sum AS rating_sum, content_rating.rating_count AS rating_count, categories.id AS CID FROM ajbz4_content AS content LEFT JOIN ajbz4_categories AS categories ON categories.id = content.catid LEFT JOIN ajbz4_content_frontpage AS frontpage ON content.id = frontpage.content_id LEFT JOIN ajbz4_users AS users ON users.id = content.created_by LEFT JOIN ajbz4_content_rating AS content_rating ON content_rating.content_id = content.id WHERE 1=1 content.id = 14615 OR content.id = 14614 OR content.id = 14605 OR content.id = 14603 OR content.id = 14602 OR content.id = 14601 OR content.id = 14600 OR content.id = 14595 OR content.id = 14594 OR content.id = 14593 OR content.id = 14580 OR content.id = 14579AND ( content.id = 14615 OR content.id = 14614 OR content.id = 14605 OR content.id = 14603 OR content.id = 14602 OR content.id = 14601 OR content.id = 14600 OR content.id = 14595 OR content.id = 14594 OR content.id = 14593 OR content.id = 14580 OR content.id = 14579) AND categories.published = 1 ORDER BY content.created DESC

**Comment by dziudek** [comment]
Please don't use NSP GK4 - it is old and unsupported version of the module. Regarding your issue - it seems that items ordering is not selected what causes a SQL error.

**Comment by user2305** [comment]
Hello. Sorry for the inconvenience. The error was on our part. We have corrected it.
