### ISSUE TITLE
Error: No articles to display

### ISSUE THREAD

**Issue by bopomo** [GavickPro/News-Show-Pro-GK5#254]
I got "Error: No articles to display" instead of the articles I wish to display.  I searched the Internet for possible solutions, but none seems to be applicable.  I set it to no caching.  I tried the various Time Offset.  
![2015-01-27 15 49 22](https://cloud.githubusercontent.com/assets/10721679/5915228/04ec95d6-a63e-11e4-94b2-31668c0c6c63.jpg)

**Comment by dziudek** [comment]
Hello,

Please send me your access details - I will try to analyze your issue in my free time.
