### ISSUE TITLE
Make NSP titles actual links

### ISSUE THREAD

**Issue by tedyd** [GavickPro/News-Show-Pro-GK5#255]
Hi,I am using Joomla 3.3.6, K2 2.6.9 and News 2 template. I like a lot NSP module, but I would like the category names to be actual links. Because I've been told by some of my readers that they try to click on them and nothing happens. See here: http://www.zdravduh.com/. I mean these: ЛИЧНИ ФИНАНСИ, ЗДРАВЕ etc.

**Comment by dziudek** [comment]
Hello,

For me links are working fine.

**Comment by tedyd** [comment]
What I meant is that ЛИЧНИ ФИНАНСИ and ЗДРАВЕ etc. are not links at all. And it is logical that they lead to the correspondent category.

**Comment by dziudek** [comment]
I forgot - as I see you are using our premium template - could you provide me your username connected with your membership?

**Comment by tedyd** [comment]
my username is: te_dyd

**Comment by dziudek** [comment]
You have to configure the URLs using the gk module links plugin - it adds additional block in the module settings:

![news2_-_administration_-_module_manager__module_news_show_pro_gk5](https://cloud.githubusercontent.com/assets/22004/6029570/b573e392-abf1-11e4-85eb-59d7b09a8ec1.jpg)

**Comment by tedyd** [comment]
Many thanks for your answer. I am really sorry, but I don`t have this module title links setting in my
News-Show-Pro-GK5 module - it is missing. And I can`t find a download link for such plugin. Please help me with that. 
  
  Best Regards,  Teodora







 -------- Оригинално писмо --------

От: Tomasz Dziuda notifications@github.com

Относно: Re: [News-Show-Pro-GK5] Make NSP titles actual links (#255)

До: GavickPro/News-Show-Pro-GK5  

Изпратено на: 03.02.2015 23:12



 
 
  
You have to configure the URLs using the gk module links plugin - it adds additional block in the module settings:

**Comment by dziudek** [comment]
This plugin is available in our rest files packages under the plugins directory.

**Comment by tedyd** [comment]
Oh, sorry. My mistake. I was wondering why rest files could not be installed properly. I had to unzip first obviously and install the plugins from there :)







 -------- Оригинално писмо --------

От: Tomasz Dziuda notifications@github.com

Относно: Re: [News-Show-Pro-GK5] Make NSP titles actual links (#255)

До: GavickPro/News-Show-Pro-GK5  

Изпратено на: 04.02.2015 10:06



 
 
  
This plugin is available in our rest files packages under the plugins directory.
