### ISSUE TITLE
NSP GK5

### ISSUE THREAD

**Issue by ianpics** [GavickPro/News-Show-Pro-GK5#256]
Having some major issues with this module after upgrading my site and templates to the current status .... never had this before but ... 
Most of the portals don't work correctly mainly in layout and alignment
Most of the portals do not take instructions via the article layout config tab (admin)
The title cannot be controlled to give a certain number of characters/words 
Certain information can neither be turned on or off 

please check expix.co.uk front page using the product II Gallery where This is an example.
I ave used GK4 (and still do) on other pages and this seems to still be working correctly although the admin layout is broken ...  
Can anyone shed any light? ... 
P.S. I'm not a developer so please make any answer understandable for an idiot ;-)

**Comment by dziudek** [comment]
Hello,

The NSP GK4 is no longer supported - please use NSP GK5

**Comment by ianpics** [comment]
Sorry but that answer is not helpful or even an answer!
I AM using NSPGK5 but CAN NOT get it to work properly .... 
until such time that I can actually configure NSP GK5  I will keep using a module that is still working it would be suicide to switch to something I cannot configure!
Please can you answer the question above can you tell me why the configurations of this module are not working?????????

**Comment by dziudek** [comment]
Sorry my mistake - I've wrongly read your issue. 

Regarding the problem - portal modes have their custom options and not all settings affects their layout - especially the ones located in the layout tab. So if you are using the portal mode you should rely on the portal mode settings tab.

**Comment by ianpics** [comment]
Hi Thanks for this ... 
however I have tried to change the settings via each portals controls.
I am stuck on how to make the heading restricted to 10 charaters/words (or 20 or 30) as well as the rest of the controls not working.
i.e. info button 1st,2nd 3rd, etc txt visible / not visible etc ... 

They used to work on the old nsp gk4 but for some reason they have not worked for a while yet keep the original settings I applied.
It does seem really strange. See attached images to show the settings I have used and that do not seem to work.
I am wondering if there is a conflict with another module? or the template itself??

Regards

Ian 
              
              
              
              
Date: Thu, 12 Feb 2015 01:57:09 -0800

**Comment by ianpics** [comment]
Hi Thanks for this ... 
however I have tried to change the settings via each portals controls.
I am stuck on how to make the heading restricted to 10 charaters/words (or 20 or 30) as well as the rest of the controls not working.
i.e. info button 1st,2nd 3rd, etc txt visible / not visible etc ... 

They used to work on the old nsp gk4 but for some reason they have not worked for a while yet keep the original settings I applied.
It does seem really strange.
              
              
              

Date: Thu, 12 Feb 2015 01:57:09 -0800

**Comment by dziudek** [comment]
But do you know that portal modes in NSP GK5 and NSP GK4 are not the same and have different options and layout? Most probably you will have to edit the controller.php directly: https://github.com/GavickPro/News-Show-Pro-GK5/blob/master/mod_news_pro_gk5/tmpl/portal_modes/product_gallery_2/controller.php
