### ISSUE TITLE
Issues with NSP GK5 and Joomla 3.4?

### ISSUE THREAD

**Issue by ckubs** [GavickPro/News-Show-Pro-GK5#257]
Hello, do you know about some issues between your news module and the new Joomla release( now on beta 2)?

I did the upgrade( I know it's not reccomended to do it in live sites but, now I did it already) all my NSP GK5 I opened and saved after that are making my site to go 404 on the frontpage and output this SQL error: 
```1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 0,10' at line 21 SQL=SELECT content.id AS iid FROM dh5w1_content AS content WHERE content.state = 1 AND content.access IN (1,1,2,3) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-02-04 09:39:48' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-02-04 09:39:48' ) AND ( content.catid = 106 OR content.catid = 111 OR content.catid = 112 OR content.catid = 113 OR content.catid = 114 ) AND content.language in ('ro-RO','*') ORDER BY content. DESC LIMIT 0,10;```

Also, the modules admin screens look weird with the settings for all the templates displayed, not like before, to have the settings for title overlay only when title overlay template is selected... etc.

**Comment by dziudek** [comment]
First of all please check if the order by field in the module data source settings is selected. We will test our extensions when the J!3.4 RC will be released.

**Comment by ckubs** [comment]
@dziudek I can't find any order by field field with all those settings outputted in the same time.

Well, since I can't rollback my Joomla upgrade from beta to 3.3.6 I have to disable the modules and wait for the RC when you would make the compatibility tests.

**Comment by witter-gmbh** [comment]
I've got the same error.
After update to joomla 3.4 today same error message.
Tried to set the order field again but the dropdown is empty.
Any idea?

**Comment by dziudek** [comment]
@witter-gmbh - did you tried to use the latest version of the module - v.1.8.0.6?

**Comment by witter-gmbh** [comment]
i am using v.1.8.0.5
where can i get 1.8.0.6?

**Comment by dziudek** [comment]
From our download section or from joomla update section.

**Comment by witter-gmbh** [comment]
OK, i got it working again using the latest version 1.8.0.6.
Thank you for your help!

**Comment by kimbalear** [comment]
Today upgrade to joomla 3.4.0 and NSP5 module gives me error 1064, please it is urgent

**Comment by witter-gmbh** [comment]
Try using latest version: 1.8.0.6 that worked for me!

**Comment by Levetofte** [comment]
I have the same problem and have updated to 1.8.0.6 without any luck, please help

**Comment by dziudek** [comment]
@Levetofte - did you resaved the module settings? Please make sure that the ordering field under the data source tab is corretly set.

**Comment by pnaadmin** [comment]
hello, I have the same problem and have updated to 1.8.0.6 , the News order button is not working to select something

**Comment by dziudek** [comment]
@pnadmin - please refresh your browser cache.

**Comment by pnaadmin** [comment]
thank you dziudek, everything is fine.

**Comment by Levetofte** [comment]
It's working now, thank you! ;o)

**Comment by wilsonjda** [comment]
I have the same problem, I update to the last versión 1.8.0.6, clean browser and Joomla caché, delete the module and create it again so I have this error.

Error: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 0,12' at line 21 SQL=SELECT content.id AS iid FROM t01sd_content AS content WHERE content.state = 1 AND content.access IN (1,1) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-03-08 05:34:50' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-03-08 05:34:50' ) ORDER BY content. DESC LIMIT 0,12;

**Comment by dziudek** [comment]
@wilsonjda - sorry but it seems that you haven't refreshed your browser cache or the module was wrongly update, because the described solution is working for everybody.

**Comment by TomppaW** [comment]
Hi, I`ve been struggling with this for a while and finally found out what´s causing 1064.
I found some old GK4 com_modules left overs in the databases assets. Removed it and everything works fine again.

**Comment by xristoph** [comment]
I too am having this problem now, just began after updating joomla from 3.3.6 to joomla 3.4.3. I've updated the News Show Pro AND verified the settings are correct in Data Source. Oddly enough I'm unable to to click the News Order drop down, it's acting as if no options are present.

TomppaW I also have these "left over" older modules showing in my Componenets drop down but don't know how to remove them. Can they be removed from the control panel or is it a direct MySQL type of modification needed?

**Comment by dziudek** [comment]
@xristoph - as I wrote earlier - please refresh your browser cache or please use a different browser.

**Comment by xristoph** [comment]
Seriously? I know how to refresh my cache....
I used 3 browsers on a PowerBook, 3 on an iMac and 3 on a PC from work....tried from my mobile that had never visited the site previously.

What nex?  Cuz that did not fix your freaking template or components problem / bu!!!

----- Reply message -----

**Comment by xristoph** [comment]
Problem / bug

**Comment by dziudek** [comment]
@xristoph - please send me your back-end access to dziudek[at]gavick[dot]com

**Comment by TomppaW** [comment]
@xristoph  You can remove the fields in MySQL.

**Comment by xristoph** [comment]
@dziudek , I just emailed from a Gmail account, thanks for looking into it. Thank you for the intel TomppaW

**Comment by xristoph** [comment]
@dziudek I got it working. Found a thread on the Gavick site, clarifying to refresh browser with NSP module open, which defanitely helped me have the ability to choose Sort type. Problem resolved... guess I "don't know" how to refresh my browser LOL

**Comment by socialcastja** [comment]
I have tried all the recommendations. I just updated to the latest version. I am using the headline theme. http://onthebrinkmag.com/v3/ ![screen shot 2015-10-04 at 11 53 15 am](https://cloud.githubusercontent.com/assets/9833694/10268966/866e2894-6a8e-11e5-86c2-d8ca39e061e4.png)

**Comment by dziudek** [comment]
@socialcastja - please use a different browser and then resave the module configuration, because you must have the issue with your browser cache as other people.

**Comment by biemar** [comment]
Witam . Mam najnowszą zaktualizowaną joomla i rozsypał mi się cały moduł news show pro 5 od strony zaplecza. Zmieniając cokolwiek w nim wywala błąd i strona nie działa. Jak to naprawić?
Poniżej link do zrzutu
[http://zsee.nazwa.pl/zrzuty/news.jpg](url)
I jeszcze taki błąd jak dokonam zmiany w ustawieniach 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DESC LIMIT 0,12' at line 22
i jeszcze taki problem

1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND c.extension = 'com_content' AND c.published = 1' at line 12
