### ISSUE TITLE
Pomylka w stylach

### ISSUE THREAD

**Issue by teitbite** [GavickPro/News-Show-Pro-GK5#259]
Kiedy wybieramy w Module mode "Centered Title Overlay" to otwiera sie panel dla "Product Gallery - Portal Mode Settings" a nie to co chcielismy.

https://www.gavick.com/forums/255/center-title-overlay-not-showing-setting-43574?p=218665#p218665

**Comment by dziudek** [comment]
Fixed: https://github.com/GavickPro/News-Show-Pro-GK5/commit/08753410b25bd9fedebcb18e8fad977742bc5379 will be available in the next update.
