### ISSUE TITLE
Is it possible ad cooments after link title in standard mode..?

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#260]
Hello!

I am using your module, i would like to ask is it possible to add ad cooments after link title in standard mode..? In optinon i can add cooments only in article title, but i can not ad comments in link layout.

So how can i add comments after link title..?

Thanks!

p.s. great module

**Comment by dziudek** [comment]
Hello,

Unfortunately it is not possible - the link layout can contain only title and short description.
