### ISSUE TITLE
Issues with NSP GK5 and Joomla 3.4

### ISSUE THREAD

**Issue by razi3el** [GavickPro/News-Show-Pro-GK5#261]
Hello, do you know about some issues between your news module and the new Joomla 3.4 and 
NSP GK5 v.1.8.0.6. I got this error when i  publish NSP.

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 0,12' at line 21 SQL=SELECT content.id AS iid	FROM jos_content AS content WHERE content.state = 1 AND content.access IN (1,1,2,3,6) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-02-25 20:26:39' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-02-25 20:26:39' ) ORDER BY content. DESC LIMIT 0,12;

**Comment by dziudek** [comment]
Please go to the module settings - please make sure that you have refreshed your browser cache. If yes, please make sure that the ordering field under the data sources tab is filled properly. If yes - please save the module settings.

**Comment by razi3el** [comment]
not  working

**Comment by dziudek** [comment]
@razi3el - please send me an administrator access to your website to dziudek[at]gavick[dot]com

**Comment by bertmert** [comment]
Issue confirmed by a user at german joomla portal:
http://www.joomlaportal.de/joomla-3-x-allgemeine-fragen/317938-fehlermeldung-1064-a.html#post1583803

**Comment by dziudek** [comment]
@bertmert - this issue doesn't exist in the newest version of the module - confirmed by ~20 cases where I have recommended update :)

**Comment by wideoch** [comment]
Ich habe die neueste Version, Cache gelöscht, Datenbank ok. Deutsch OK. 
Französisch mit Fehler:
latest version, cache, database OK. German OK.
French with error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 0,16' at line 21 SQL=SELECT content.id AS iid FROM jsmwh_content AS content WHERE content.state = 1 AND content.access IN (1,1,5) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-02-26 12:38:07' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-02-26 12:38:07' ) AND ( content.catid = 25 ) AND content.language in ('fr-FR','*') AND content.featured = 0 ORDER BY content. DESC LIMIT 0,16;

**Comment by dziudek** [comment]
@wideoch - did you resaved the module after upgrade? Please make sure that the ordering field under the data source is properly set.

**Comment by wideoch** [comment]
Es funktioniert nicht!!!!
It does not work !!!!

Mit freundlichen Grüssen
Ernst Wicki
________________________________
Himmelsbergstrasse 3
8617 Mönchaltorf

+41 44 948 14 22
+41 79 884 57 55

Von: Tomasz Dziuda 
Datum: Donnerstag, 26. Februar 2015 19:13
An: GavickPro/News-Show-Pro-GK5 
Cc: wideoch 
Betreff: Re: [News-Show-Pro-GK5] Issues with NSP GK5 and Joomla 3.4 (#261)

@wideoch - did you resaved the module after upgrade? Please make sure that the ordering field under the data source is properly set.

**Comment by dziudek** [comment]
For other users it is working - please make sure that the order field is correctly set - it must work.

**Comment by Cyberek** [comment]
Seems that there is a problem with "The Video List - Portal Mode" after J3.4 update:
http://www.gorast.com/eusnov/mk/profil/media
It doesn't retrieve thumbnails correctly.

(https://www.gavick.com/forums/255/video-list-portal-mode-settings-broken-after-j3-4-0-update-43961?p=220045#p220045)

**Comment by dziudek** [comment]
User should try to do a resave - I've tested our News 2 installation with the same portal mode and there is no similar issue.

**Comment by Pandorian** [comment]
Same problem here. If I go to the order field, it is blank as you can see here -> http://i.imgur.com/hMBWDKL.png

If it is helpful for you, I upgraded to J! 3.4, everything was fine, but when I made a change at the module and saved it, it was then that the 1064 error appeared.

I uninstalled the module and then re-installed it, but the problem appeared again.

**Comment by dziudek** [comment]
@Pandorian - it was mentioned so many times - please refresh your browser cache or use different browser - it must works if you have v.1.8.0.6

**Comment by katika555** [comment]
not working, after update, 
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND c.extension = 'com_content' AND c.published = 1' at line 12 SQL=SELECT c.id AS CID FROM db2_categories AS c LEFT JOIN db2_content AS content ON c.id = content.catid WHERE 1=1 AND ( content.id = ) AND c.extension = 'com_content' AND c.published = 1
any help please,

**Comment by dziudek** [comment]
@katika555 - in you case you have to also check your data source configuration for missing article/category ID configuration.

**Comment by 007raspc** [comment]
hi.
GK5 module work with joomla news.
but when i try with wirtuemart...see screenshot
![444](https://cloud.githubusercontent.com/assets/12112804/7333333/273fa72e-eb74-11e4-9eb2-419ef3899242.JPG)
sadness (

**Comment by dziudek** [comment]
@007raspc - please check of you have properly configured the data source i.e. If you have provided the product ids if the vm products display is set as data source.

**Comment by 007raspc** [comment]
![666](https://cloud.githubusercontent.com/assets/12112804/7333932/77345fda-eb89-11e4-9874-72cfedcd9bc7.JPG)
![777](https://cloud.githubusercontent.com/assets/12112804/7333933/7b939672-eb89-11e4-9342-f8ddac36ec66.JPG)
Here is my settings.
what's wrong?
thank you for fast answer!

**Comment by dziudek** [comment]
You have empty virtuemart products field - it must contains product ids separated by comma

**Comment by 007raspc** [comment]
![888](https://cloud.githubusercontent.com/assets/12112804/7334127/0ba62a24-eb92-11e4-8b00-70c2030da0b4.JPG)
added id, but error(

**Comment by 007raspc** [comment]
good news)
work it!
Time offset i set by 1, but i need in 0

**Comment by marionic** [comment]
I have upgrade the module and i have the same error. I have buy some gavick templates and all of theme have errors in this module.

**Comment by vahegalstyan** [comment]
Hi I have the same problem, pleas tell me why it happened and how to fix it.
This is my error 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY content.created DESC LIMIT 0' at line 12 SQL=SELECT content.id AS id FROM bywgf_k2_items AS content WHERE content.published = 1 AND content.trash = 0 AND content.access IN (1,1) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-07-22 14:51:13' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-07-22 14:51:13' ) AND ( ) ORDER BY content.created DESC LIMIT 0,4;

**Comment by dziudek** [comment]
@vahegalstyan - fisrt of all - are you using the newest version of the module?

**Comment by vahegalstyan** [comment]
yes i use newest version

2015-07-23 11:55 GMT+04:00 Tomasz Dziuda <notifications@github.com>:

**Comment by vahegalstyan** [comment]
At first I want understand what imitate this problem

2015-07-23 11:56 GMT+04:00 Vahe Galstyan <vgalstian90@gmail.com>:

**Comment by vahegalstyan** [comment]
Can anyone help me?

2015-07-23 11:59 GMT+04:00 Vahe Galstyan <vgalstian90@gmail.com>:

**Comment by dziudek** [comment]
Please make sure that you have provided article IDs when you have selected option of displaying K2 articles. If it won't help - please post here a screenshot of your data source tab.

**Comment by vahegalstyan** [comment]
now my site working good because i backup db, I want only understand why it happen for resolving future problems.

**Comment by dziudek** [comment]
It is hard to say, maybe you have different data source settings earlier?

**Comment by vahegalstyan** [comment]
no I think, can this problem occure when I puted more items, or when  deleted items??

**Comment by dziudek** [comment]
If you delete all items then this issue can occur.

**Comment by vahegalstyan** [comment]
ok Thanks , if I have any problem I will write you)
Thank you very much

**Comment by vahegalstyan** [comment]
but when You delete one  item which have tags, another mysql error will show )

**Comment by dziudek** [comment]
Please send me an e-mail with back-end and FTP access to dziudek[at]gavick[dot]com - I will look at this issue at weekend.

**Comment by vahegalstyan** [comment]
ok Thanks.

**Comment by ANDiTKO** [comment]
**Solution that worked for me:**
Go to Basic Settings (under your GKnews module) -> and Load the original.json configuration.
Then re-save your module.

That worked for me :)

**Comment by Diversesolution** [comment]
Hi Guys,

After the last gk5newspro update all the modules disappeared : http://www.lostrappoquotidiano.it

any suggestions on how to fix this?

Thanks
Luigi

**Comment by biemar** [comment]
Witam . Mam najnowszą zaktualizowaną joomla i rozsypał mi się cały moduł news show pro 5 od strony zaplecza. Zmieniając cokolwiek w nim wywala błąd i strona nie działa. Jak to naprawić?
Poniżej link do zrzutu
[http://zsee.nazwa.pl/zrzuty/news.jpg](url)
I jeszcze taki błąd jak dokonam zmiany w ustawieniach
You have an error in your](url) SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DESC LIMIT 0,12' at line 22
i jeszcze taki problem
1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND c.extension = 'com_content' AND c.published = 1' at line 12
