### ISSUE TITLE
K2 with Storefront: cant display blog content

### ISSUE THREAD

**Issue by Adwans** [GavickPro/News-Show-Pro-GK5#262]
Hello,
I can't see "regular" K2 Items (path /blog/item/... ) but only items from /template/k2/k2-categories/... are displayed on Blog page as default. Site is here: dom.hekko24.pl . Site was installed from Gavick Ready-Pack (all in one).
New added items and older items from "pre-installed gavick" categories (eg. Style News) appear correctly, but "my" K2 items/ categories fail to. Why some "K2" categories paths are diferent: /template/k2/ and not /blog/item/... ?  Is there a component which controls it? 
Regards Zb

**Comment by dziudek** [comment]
Hello,

Most probably you have a module on the mainbody module position and your articles are displayed on the homepage - in this case, please create menu items for your K2 categories.

**Comment by Adwans** [comment]
Hello, 
I had already created both K2 cats and K2 items, but. Since installation was "out-off-the-box" , GT items (You now, from cat's "news show"..."Style news" ..."I love February ..." and so on) are displayed correctly. My NEW cat's /items not.  I also tried to clone "style news" category, but new cloned category apears/displays not well, rather like my new cat's/items. Cant  see my items on the Blog page, only in the categiories. Maybe it is controlled otherwise?  Not with K2 component? Default site lang is Norwegian now - but changing lang value for K2 elements do nothing . (If i didnt understand You well,  write in PL please). Regards.

**Comment by dziudek** [comment]
Jeszcze raz - czy nowe kategorie mają własne pozycje w menu?

**Comment by Adwans** [comment]
Of course! Mają.

**Comment by dziudek** [comment]
Proszę o przyłady linków, które nie działają, bo jedyny jaki znalazłem to: http://dom.hekko24.pl/index.php/blog/item/279-carport-forarbeid i on u mnie działa.

**Comment by Adwans** [comment]
Witam, małem mały młyn. OK, Teraz w blogu na stronie (czyli na stronie komponentu K2)  wyłączyłem wszystkie kategorie od Was - "style news" "celebrity news" fashion  news... 
Proszę zobaczyć, co wyświetla się na stronie komponentu.  U mnie jest _Blank.
http://dom.hekko24.pl/index.php/blog
Pomimo aktywnych kategorii - co łatwo sprawdzić wchodząc w menu kategorii. Z góry dziękuję za pomoc i za zainteresowanie.

**Comment by dziudek** [comment]
Proszę na naszym forum wysłać mi wiadomość PM z danymi dostępowymi do panelu administracyjnego oraz dane dostępowe FTP. Tutaj wątek zamykam bo jest on niezwiązany z modułem NSP GK5.
