### ISSUE TITLE
How to put brackets around article comments..?

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#263]
Hello!

I would like to ask. How to put brackets around article comments..? To look more stylish

Comments Source is Jcomments, using joomla 3 and latest yor module

Is it possible some how to do that..?

Thanks!

**Comment by dziudek** [comment]
Hello,

You can just wrap the %COMMENTS inside the article info format into brackets.

**Comment by sirdna** [comment]
Thanks worked for me!
