### ISSUE TITLE
Module does not show more items added to the component k2

### ISSUE THREAD

**Issue by fabricioventura** [GavickPro/News-Show-Pro-GK5#265]
Hello!

I have a big problem.
The module does not show more items added to the component k2.
He is showing me only 7 items, but I have 9 items registered on k2 in categories.
I've tried everything, cleaned cache of Joomla ok, browser cache ok, filters ok, Source ok,  etc ... etc ...

I'm using:
-Joomla 3.4
-K2 - 2.6.9
-News Show Pro GK5 - 1.8.0.6

Why is this happening? Is this a bug?

**Comment by fabricioventura** [comment]
Problem solved!

there was something blocking the changes.

To resolve needed to install another extension showing k2 of articles on the home page, and after that the changes in the News Show Pro GK5 - 1.8.0.6. were applied.

I do not know what happens, but this solved ára me.

I do not know what can be the explanation!

Thank you very much!

**Comment by rodolfoalbuquerque** [comment]
Hey, friend; I appreciate your help, but didn't worked for me.

I tried to download, but it's not free... :(

I really need it, could you help me, please?
