### ISSUE TITLE
How to put article comment count after the article title...

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#267]
Hello!

I would like to ask How to put article comment count right after the article title...

I Need this kind a layout: News title (2 comments) 

Get this kind layout:
News title 
(2 comments) 

As i understand i have to modify "Information block" settings, i try  "Information floaiting" settings left right, but can get work for me

Can you please give me an advice on this thing, will be gratefull

Thanks for your previous answers a lot!

**Comment by dziudek** [comment]
Hello,

What about this issue: https://github.com/GavickPro/News-Show-Pro-GK5/issues/263#issuecomment-77781124 ?
