### ISSUE TITLE
[Events List] mode improvement idea.

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/News-Show-Pro-GK5#270]
There was a request to add a support for nor incoming events. If there are no incoming events some simple information might show instead of an empty space. What do you think?
(https://www.gavick.com/forums/university-joomla3/no-events-display-44469?p=223002#p223002)

**Comment by dziudek** [comment]
Done: https://github.com/GavickPro/News-Show-Pro-GK5/commit/bc401598050433fc40fc4e2a51c5fd35449dda14

It will be available in v.1.8.3
