### ISSUE TITLE
GK5 not showing title on the frontend

### ISSUE THREAD

**Issue by mrcpina** [GavickPro/News-Show-Pro-GK5#271]
Hi there i am new here, and new as well at developing website using Joomla.
I am using News show pro gk5 to display news and event and i set the module title as such, the problem is that i want the module to display the title, but is not working even with the title toggle set to SHOW position.
Help!

**Comment by dziudek** [comment]
Hello,

Please make sure that your module position uses a style which is able to show module title.

**Comment by mrcpina** [comment]
The position does show titles of the articles, but i am not sure how to check if its able to show modules title!

**Comment by dziudek** [comment]
Please check in the code the style attribute for the <jdoc:module> element.
