### ISSUE TITLE
Comments enabled for News Show Pro GK5 module in Joomla 2.5.27

### ISSUE THREAD

**Issue by JoePiscapo** [GavickPro/News-Show-Pro-GK5#272]
Hello,

I want to have comments enabled on my new site for articles within the News Show Pro GK5 module using Joomla 2.5.27 and I have no idea how.  Can someone please help?

**Comment by dziudek** [comment]
Hello,

Sorry but it is not possible to display comments list under NSP GK5 entries, the only thing which you can display is link to the comments - you can do it by adding in the info block format field the phrase %COMMENTS

**Comment by JoePiscapo** [comment]
Ok, I did that, under the "info format", thanks.  I also have %DATE %HITS %CATEGORY and %AUTHOR.  However, I can't see anything active on my page.  How can I do that?

thanks again.

**Comment by dziudek** [comment]
Under the article layout tab you can enable every element - title, image, text, info block etc.

**Comment by JoePiscapo** [comment]
Apparently those are set to "on", and have been.  I have under article layout: "Header order, Image order, Text order, Information order, and second information order" all turned on with an order number selected.

**Comment by dziudek** [comment]
Please send me an access to your back-end with ID and URL with the problematic module on your website to dziudek[at]gavick[dot]com.

**Comment by JoePiscapo** [comment]
Ok will do...

**Comment by JoePiscapo** [comment]
Hey again, I know that technically one cannot display a comments list under NSP GK5 entries, but I really want to be able to do so. What would be your suggestion? Upgrade to something else perhaps?

**Comment by dziudek** [comment]
I didn't used this kind of extensions (with comments lists) so I'm unable to help you with finding a solution for this case.
