### ISSUE TITLE
Add a "see all" type link option

### ISSUE THREAD

**Issue by charmedworks** [GavickPro/News-Show-Pro-GK5#273]
We are using five instances of the News Show Pro GK5 to show article titles, dates and links to different selections of categories.  Everything works great EXCEPT we'd like to have a field in the administration of the module to add a link to "see all" (Preferably where we could write in the text for the link and then select the menu item to link to OR paste in the URL of the link), then this link would appear at the end of the list of items the module is displaing (Preferably in a <Div> so we can style it separately.) This would be different for each instance of the module that we are using so we'd want to be able to set it up via the module administration.

**Comment by dziudek** [comment]
Hello,

The only way to achieve this is use the link layout and then specify under the "Links layout" tab two options: "Link URL" and "Link label"

**Comment by charmedworks** [comment]
Thank you.  I will take a look at that option, and report back here.

**Comment by charmedworks** [comment]
Hello, thank you for directing me to the Links Layout area.  I was not fully aware of what this area would do.  It comes very close to solving our issue.  I am able to add the "link URL" and the "link label" and these display fine, exactly as we'd like.  However, because we do not want any actual links to appear above the two I have to set the number of links to appear to "1" and then set the amount of title text and intro text to "-1" so that none displays. So, it is sort of a work around in the settings although it works GREAT for the display we are wanting to achieve.  Thank you!
