### ISSUE TITLE
Fatal error after upgrading to j3.4.1

### ISSUE THREAD

**Issue by gulamc** [GavickPro/News-Show-Pro-GK5#274]
Hi,

After upgrading my site from Joomla v3.3.6 to 3.4.1, I get fatal error as follows:

Fatal error: Call to a member function init() on a non-object in /home/nssfnew/public_html/templates/rt_nuance/error.php on line 15

If I disable NSP GK5 then the site loads ok. I also tried to update the extension to v1.8.2 but I still get the same error.

Is your extension not compatible with j3.4.1?

Please advice.

Gulam

**Comment by dziudek** [comment]
Hello,

The error which you are getting is a theme error not our module error. Most probably it wants to display the 1064 error - please:

1) Clear your browser cache or use different browser
2) Go to the module settings
3) Resave the module settings.

**Comment by gulamc** [comment]
Hi,

I did all that but no luck.

Here is what happens on the site:

http://webserver3.ebiz.co.tz

The moment I unpublish the module NSP GK5, the site loads.

Gulam

**Comment by dziudek** [comment]
Please rename the error.php file in your template to __error.php and then please copy here your error message.

**Comment by gulamc** [comment]
Sorry made a mistake in giving you the actual site. Its as follows

http://webserver3.ebiz.co.tz/~nssfnew

Gulam

**Comment by gulamc** [comment]
The error reads as follows:

1064
You have an error in your SQL syntax; check the manual that corresponds to
your MySQL server version for the right syntax to use near 'DESC LIMIT
0,19' at line 21 SQL=SELECT content.id AS iid FROM mx3of_content AS content
WHERE content.state = 1 AND content.access IN (1,1) AND (
content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <=
'2015-04-07 10:38:08' ) AND ( content.publish_down = '0000-00-00 00:00:00'
OR content.publish_down >= '2015-04-07 10:38:08' ) AND ( content.catid = 20
) ORDER BY content. DESC LIMIT 0,19;


Gulam

**Comment by gulamc** [comment]
The error reads as follows:

1064
You have an error in your SQL syntax; check the manual that corresponds to
your MySQL server version for the right syntax to use near 'DESC LIMIT
0,19' at line 21 SQL=SELECT content.id AS iid FROM mx3of_content AS content
WHERE content.state = 1 AND content.access IN (1,1) AND (
content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <=
'2015-04-07 10:38:08' ) AND ( content.publish_down = '0000-00-00 00:00:00'
OR content.publish_down >= '2015-04-07 10:38:08' ) AND ( content.catid = 20
) ORDER BY content. DESC LIMIT 0,19;

**Comment by dziudek** [comment]
Please try to use a different browser to configure the module and resave its settings, because it is a definitely your browser cache issue - it shows you an old version of the back-end with a bug which causes this SQL error after module settings save.

**Comment by gulamc** [comment]
Ok, I used Chrome to save the settings That did the trick, the site loads
ok. Thank you very much.

Gulam
