### ISSUE TITLE
PHP 5.5.22

### ISSUE THREAD

**Issue by gwsdesk** [GavickPro/News-Show-Pro-GK5#276]
Current version fully working with PHP 5.5.22? We have a client who has 3 sites with this module on one server that runs on PHP 5.4.31 and we wish to upgrade that server to PHP5.5.22 we need to know if that throws the module in disarray.

**Comment by dziudek** [comment]
Hello, 

The only requirement is PHP > 5.3.10 - I've checked the module few times on PHP 5.6 and there was no problems, but there is a lot of possible configurations - if you will find any issue, please let us know - we will fix it ASAP.
