### ISSUE TITLE
Fatal error adding %TAGS to info

### ISSUE THREAD

**Issue by antoniotheant** [GavickPro/News-Show-Pro-GK5#279]
Hello
adding %TAGS to info format I break the site, getting only this warning:

Fatal error: Class 'TagsHelperRoute' not found in /web/htdocs/www.xxx.it/home/modules/mod_news_pro_gk5/tmpl/com_content/view.php on line 183

any suggestion?

**Comment by dziudek** [comment]
Hello,

Which version of Joomla! are you using?

**Comment by antoniotheant** [comment]
3.4.1

**Comment by dziudek** [comment]
Please apply the following patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/7c5e7b6d54f5a80109a955ebd6b2d83a623c32e3

**Comment by antoniotheant** [comment]
Thank you. I don't how to exactly apply the patch, re-download the entire .zip file and install it?

**Comment by dziudek** [comment]
Please download this package: https://github.com/GavickPro/News-Show-Pro-GK5/archive/J!3.0_compatible.zip and reinstall it.

**Comment by antoniotheant** [comment]
Thanks a lot, it works fine.
Just another question: do you know how to show tags in Article Category blog view and front page for Joomla core content (not using your module)?

**Comment by dziudek** [comment]
It should be available to enable the tags display in the content component settings and inside the category/item settings.
