### ISSUE TITLE
Information Block disappear with edited articles

### ISSUE THREAD

**Issue by seadas71** [GavickPro/News-Show-Pro-GK5#281]
Hi guys
I'm using News Show Pro Gk5 1.82
I've this issue.
Scenario is this
I've created module and choose "data source" and I saw all perfect...but if edit something on item or articles Data disappear
If I open articles to full page data is displayed...only in NSP Gk5 is not shown...but only if I edit articles
Even article Preview disappear
What' up? 
Thanks

**Comment by dziudek** [comment]
Hello,

Which date is selected in the ordering and how is set the article ordering (DESC or ASC)? The missing articles appeared later in the module again?

**Comment by seadas71** [comment]
Hi ..
first thing thanks for answer!
In this situation, I dont modify nothing about ordening article (desc or ASC). 
Only thing that I do is modify article (item) of source category (both kind of category...joomla or k2)
To explain me better, please see attachment
this before modify article
![nsp-gk5-premodifica](https://cloud.githubusercontent.com/assets/12023714/7230624/ee389eb6-e76f-11e4-91af-1c1f7ebf7bd3.jpg)

this is what I see after modify...only article modified or new has this problem
![nsk-gk5 postmodifica](https://cloud.githubusercontent.com/assets/12023714/7230641/13cd3da8-e770-11e4-89c0-88c9d00e73be.jpg)

Thank you very much

**Comment by dziudek** [comment]
It seems that your WYSIWYG editor removes the HTML5 tags which are used to display these parts - please try to use the "None" editor in the back-end.

**Comment by seadas71** [comment]
Hi.
nothing to do
With option "no editor" problem still continue.
:(

**Comment by dziudek** [comment]
But did you checked the syntax after changing the editor? Because wrong syntax could be stored earlier.

**Comment by seadas71** [comment]
No because I've this issue if I modify article name only or if I create a new one in Category on data source.
To test this I've created a new article with option "no editor"...so in this case i've a blank article..just name...and issue still continue :(

**Comment by dziudek** [comment]
But do you know that the data block is generated from the info block structure inside the article not from their date in Joomla?

**Comment by seadas71** [comment]
o_O 
Oh my god 
You mean that  Data block are generated from article?
I tested this...when I delete  this string (for example)
"Date: 02 June 2015 - 03 June 2015 7:00 am - 6:00 pm"
Date block disappear
here we go? :D 
If yes..there's another question at this point (tell me if I may open another topic or not)
How I can create events?

**Comment by dziudek** [comment]
Please ask next questions at our official support forum: https://www.gavick.com/forum because it is definitely not connected with this free module.

**Comment by seadas71** [comment]
Thank you!
:)
