### ISSUE TITLE
Module style modifications

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#282]
Hello!

We have local city news portal which is build using your news module, we want to make some modifaction:

1. comments near link articles
2. comment styling modification

I dont want to waste your time just like that, it is a "busines propoasal", i would be glad if you charge money for help, which is realy interensting to you as programmer.

Modification i think are not complicated, but i think I wont solve It via forum, because of "details"

If you could provide me with your e-mail, (answering to this post) i would like send you site name, ftp, cpanel paswords, joomla admin and image how i want it to look like, so maybe you could help me..?

Please dont say no:)

P.S. Great module

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website and visualization what do you want to achieve. If it will be easy to implement I will provide you a solution - in other case, unfortunately we are too busy for more complex custom works currently.

**Comment by sirdna** [comment]
Hello!

1. Here is our site www.publika.lv local city news portal
2. I uploud image with "How I would like to have" and "How we have know" sample.jpg
3. Basicly we would like to have cooments in brackets and link comments, and cooments must at the end of title, and if there is no cooments, we would not like to show zere, i hope image could get good understanding what is our goal.
4. Fell free to charge money, if it is not 5 min job
![sample](https://cloud.githubusercontent.com/assets/11191907/7391352/2dc8fb14-ee89-11e4-888b-fb485bc27f9f.jpg)

Anyway thanks for module, it helped our site look more like news portal

**Comment by dziudek** [comment]
You can put your comments in the brackets by changing the following code:

```php
		    	$info_comments = JText::_('MOD_NEWS_PRO_GK5_NO_COMMENTS');
		        //
		        if(isset($item['comments'])) { 
		        	if($item['comments'] == 1) {
		            	$info_comments = JText::_('MOD_NEWS_PRO_GK5_1COMMENT');
		            } else if($item['comments'] > 1 && $item['comments'] < 5) {
		            	$info_comments = $item['comments'] . ' ' . JText::_('MOD_NEWS_PRO_GK5_MORECOMMENTS');
		            } else if($item['comments'] >= 5) {
		            	$info_comments = $item['comments'] . ' ' . JText::_('MOD_NEWS_PRO_GK5_MUCHMORECOMMENTS');
		            }
		        }
```

to:

```php
                      $info_comments = '';
		       //
		        if(isset($item['comments'])) { 
		            if($item['comments'] == 1) {
		            	$info_comments = '(1)';
		            } else if($item['comments'] > 1 && $item['comments'] < 5) {
		            	$info_comments = '('.$item['comments'].')';
		            } else if($item['comments'] >= 5) {
		            	$info_comments = '(' . $item['comments'] .')';
		            }
		        }
```

in the **mod_news_pro_gk5/tmpl/com_content/view.php** file (or **mod_news_pro_gk5/tmpl/com_k2/view.php** file if you are using K2).

Regarding the comments counters in the links - unfortunately it is a more complex custom work and I'm too busy to do it.
