### ISSUE TITLE
K2 article does not popup using GK5 on 

### ISSUE THREAD

**Issue by imyque** [GavickPro/News-Show-Pro-GK5#285]
K2 2.6.7
News Show Pro GK5  1.3
Joomla! 3.2.3  
I have a site setup with the above components versions. And when I click on an article in to open it in full view, it shows in a popup with an overlay on the background.

K2 2.6.9
News Show Pro GK5  1.8.2
Joomla! 3.4.1 
After I upgraded to the versions above, when I click on an article, the browser navigates to a new page with the article, instead of the popup

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website with this issue.

**Comment by imyque** [comment]
Hello Tomasz,

You dont need to bother anymore. I found out that the issue occurs only 
when a certain module is not published. Its probably an issue with the 
template.

Thanks,
Michael.
