### ISSUE TITLE
query error on my joomla 3 site

### ISSUE THREAD

**Issue by saraee** [GavickPro/News-Show-Pro-GK5#286]
Thanks so much for great news show pro GK5. I have installed News-Show-Pro-GK5-1.3-joomla3 on my joomla 3.2.3. But when I publish the module I have below query error: 
SELECT content.id AS iid	FROM xxxxx_content AS content WHERE content.state = 1 AND content.access IN (1,1) AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-05-10 08:16:26' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-05-10 08:16:26' ) AND ( content.catid = 73 ) ORDER BY content. DESC LIMIT 0,12;
The only point is that I have imported content, category and assets table from my old joomla 2.5 site. but I don't have problem with these imported tables with my joomla.
Any idea?

**Comment by dziudek** [comment]
Hello,

Please upgrade your module to the newest version: https://github.com/GavickPro/News-Show-Pro-GK5/archive/J!3.0_compatible.zip

Then refresh your browser cache and resave your module settings.

**Comment by saraee** [comment]
Thanks so much dziudek
I installed this version of module before and again I test the newer version but still I have the problem. In the Admin part of the module I also see some errors. For example in Basic settings tab I have below lines:

**Comment by saraee** [comment]
{ "name": "Bikestore_Slider", "full_name": "BIKESTORE_SLIDER", "support": [ "com_content", "com_k2", "com_virtuemart" ], "thumbnails": true }
{ "name": "Centered_Title_Overlay", "full_name": "CENTERED_TITLE_OVERLAY", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Events_List", "full_name": "EVENTS_LIST", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": false }
{ "name": "Frontpage_Image_Overlay", "full_name": "FRONTPAGE_IMAGE_OVERLAY", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Grid_News", "full_name": "GRID_NEWS", "support": [ "com_content", "com_k2" ], "thumbnails": true }
{ "name": "Grid_Title_Overlay", "full_name": "GRID_TITLE_OVERLAY", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Highlights", "full_name": "HIGHLIGHTS", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": false }
{ "name": "JomSocial_Photos", "full_name": "JOMSOCIAL_PHOTOS", "support": [ "jomsocial" ], "thumbnails": true }
{ "name": "News_Blocks", "full_name": "NEWS_BLOCKS", "support": [ "com_content", "com_k2", "com_easyblog", "com_virtuemart" ], "thumbnails": true }
{ "name": "News_Gallery", "full_name": "NEWS_GALLERY", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "News_Slider", "full_name": "NEWS_SLIDER", "support": [ "com_content", "com_k2" ], "thumbnails": true }
{ "name": "Portfolio", "full_name": "PORTFOLIO", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Portfolio2", "full_name": "PORTFOLIO2", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Portfolio_Grid", "full_name": "PORTFOLIO_GRID", "support": [ "com_content", "com_k2" ], "thumbnails": true }
{ "name": "Product_Gallery", "full_name": "PRODUCT_GALLERY", "support": [ "com_content", "com_k2", "com_virtuemart" ], "thumbnails": true }
{ "name": "Product_Gallery_2", "full_name": "PRODUCT_GALLERY_2", "support": [ "com_content", "com_k2", "com_virtuemart" ], "thumbnails": true }
{ "name": "Speakers_List", "full_name": "SPEAKERS_LIST", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "Title_Overlay", "full_name": "TITLE_OVERLAY", "support": [ "com_content", "com_k2", "com_easyblog" ], "thumbnails": true }
{ "name": "VideoGallery", "full_name": "VIDEOGALLERY", "support": [ "com_content", "com_k2" ], "thumbnails": true }
{ "name": "VideoList", "full_name": "VIDEOLIST", "support": [ "com_content", "com_k2" ], "thumbnails": true }
config_manager

**Comment by dziudek** [comment]
Did you refeshed your browser cache after updating the module? Did you tried to use a different browser?

**Comment by saraee** [comment]
Yes dear dziudek. I have done both of them. The error is in the way that when I publish the module on home page, my home page doesn't show and the error appears.
By the way my tempalte is Hogash template. Can this point has any effect?

**Comment by dziudek** [comment]
Please send me an access to your back-end with this issue to dziudek[at]gavick[dot]com

**Comment by saraee** [comment]
Dear dziudek, I sent you an email.

**Comment by dziudek** [comment]
Sorry but your issue is most probably caused by your old version of Joomla or some 3rd party extensions which affects the back-end scripts loading - we are too busy to analyze this kind of issues as it is not strictly caused by our extension.
