### ISSUE TITLE
date are not show on home page uisng  News Show Pro GK5 

### ISSUE THREAD

**Issue by lalitabagal** [GavickPro/News-Show-Pro-GK5#289]
to show the latest event uesd  News Show Pro GK5  but date are not showing on my home page

**Comment by lalitabagal** [comment]
i check this link News Show Pro GK5 in front page: date and hour? in technical discussion forum

**Comment by lalitabagal** [comment]
i'll send you url if you need to this

**Comment by dziudek** [comment]
Hello,

Please write a topic at our official forum, because your issue seems to be connected with configuring our paid template.

**Comment by lalitabagal** [comment]
Hello,

can you send me official forum link.

**Comment by dziudek** [comment]
https://www.gavick.com/forums

**Comment by lalitabagal** [comment]
Thanks.
