### ISSUE TITLE
How to put link "More articles" after news block..?

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#290]
Hello!

I would like to ask. How to puta  link "More articles" after news block..?

I have a news webiste, i use or module in  "Standard mode" i have news block, and i would like to have that after news block, there could be link, "more articles" so could people could read more articles.

To get my idea, i have attached an image,

I can done this idea modify "Links layout"  filling the fields, Link url and link label, but i dont wana show extra links above.

So how to put a link "More articles" after news block..?

![bilde123](https://cloud.githubusercontent.com/assets/11191907/7803201/2dd18df0-0352-11e5-830b-921187519771.jpg)

Thanks

p.s. great module

**Comment by dziudek** [comment]
Hello,

In this case, please move the following fragment: https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/tmpl/default.php#L101-L112

between lines 78-79.

**Comment by sirdna** [comment]
Thanks worked for me!
