### ISSUE TITLE
NEWS SHOW PRO GK5 - Installation issues

### ISSUE THREAD

**Issue by dewaldwessels1970** [GavickPro/News-Show-Pro-GK5#291]
I installed the NEWS SHOW PRO GK5 module onto Joomla 3.4.1 and received a successfully module installation message afterwards, yet when I try to find the module in my Components menu its not visible at all. Please advise.

**Comment by dziudek** [comment]
Hello,

The News Show Pro GK5 is a module not component - please go to the menu manager and please click "New" button to add a new module instance.
