### ISSUE TITLE
News Show Pro GK5 problem with multi language site 

### ISSUE THREAD

**Issue by Omar85** [GavickPro/News-Show-Pro-GK5#292]
Dear All ,
Kindly, I have a website with multi language (English, Arabic, Kurdish) but I faced a problem in (Arabic & Kurdish) pages .. the problem summarized in bellow:-

- I have a website designed by Joomla with (yoo_katana) template and content 3 languages
(English,Arabic,Kurdish),and I have a 3 type for News menu (main menu, sidebar menu and latest news
menu) you can watch it in (iraqnic.com/sardargroup/index.php/2015)
- I made a category for each language and made a categories for News.
- The categories linked with the (Module News Show Pro GK5).
- I had finished the English pages perfectly with all menus and articles and the news appears as a wonderful face.
-The Arabic language pages all it's OK except (NEWS) doesn't appears (the page appear as empty) , I don't know why knowing I designed it just like English (NEWS) pages, you can watch it in (iraqnic.com/sardargroup/index.php/ar/2015).
Please how can I fix this problem, I need a hurry assist .

Note :- The latest news it's OK and work perfectly.
Note :- When I copy the source code of (news) in Arabic page and paste it in (MS frontpage) all the content was appear but not appear in original page !!

Thanks a lot,

**Comment by dziudek** [comment]
Hello,

as I see your issue is caused by fact that you have a RTL language page - unfortunately we didn't tested our module with RTL languages so this module doesn't support RTL languages. And fixing this issue is definitely beyond of our technical support.

**Comment by Omar85** [comment]
OK Dziudek,
Thanks a lot for your assist, but can I tale me if you will test it as soon time?

**Comment by dziudek** [comment]
So in this case it is a conflict between the used template and the module - I'm really sorry, but we are too busy for debugging this kind of issues.

**Comment by Omar85** [comment]
OK Mr.dziudek,
I'm really thank you for your time , I hope success in your work.

Thanks a lot
