### ISSUE TITLE
The font overlaps itself in the header

### ISSUE THREAD

**Issue by JoePiscapo** [GavickPro/News-Show-Pro-GK5#293]
Hello,

The header text overlaps itself when it's more than one line.  Is there any way to change this?

thanks,
Mike

**Comment by dziudek** [comment]
Hello,

Please provide an URL to your website with this issue.

**Comment by JoePiscapo** [comment]
sure. Although we are having some ip address issues at the moment...
 
arion-group.com
 
Date: Thu, 18 Jun 2015 22:32:13 -0700

**Comment by dziudek** [comment]
Please add in your CSS code:

```css
.nspArt h4.nspHeader {
  line-height: 1.2;
}
```

**Comment by JoePiscapo** [comment]
Ok, will do. But where is the CSS code? Where can I access it?
 
Thanks again,
Mike
 
Date: Fri, 19 Jun 2015 06:38:36 -0700

**Comment by dziudek** [comment]
You can add it in any CSS file used by your template.

**Comment by JoePiscapo** [comment]
I did that yesteday and to no avail. Though if I were to try to do it again I would have no idea how.  Do you mind walking me throught that process?  That would be the best!
 
Date: Mon, 22 Jun 2015 04:41:06 -0700

**Comment by dziudek** [comment]
Please just open this file: http://arion-group.com/templates/emeta/css/extensions.css and put my code at the end - it must works.

**Comment by JoePiscapo** [comment]
I DID IT! IT WORKS!
 
Thank you!
 
Date: Wed, 24 Jun 2015 05:53:18 -0700
