### ISSUE TITLE
Title not showing on News Show Pro GK5

### ISSUE THREAD

**Issue by ianandersonmedia** [GavickPro/News-Show-Pro-GK5#294]
Hi
I am using the News Show Pro GK5 module and Creativity theme. The data source is an Easy Blog 3 category, but the blog titles are not showing up under the pics on my frontpage here: http://baseservices.com.au
Am I missing something?
Thanks
Ian

**Comment by dziudek** [comment]
Hello,

The selected portal mode displays only images with links - adding showing of the title needs a custom work which is beyond of our technical support.
