### ISSUE TITLE
Module throwing error after upgrading to EasyBlog 5

### ISSUE THREAD

**Issue by internetix** [GavickPro/News-Show-Pro-GK5#295]
After upgrading Easyblog to latest release (EasyBlog 5), the module is throwing the following error when activated on page

1054
Unknown column 'content.private' in 'where clause' SQL=SELECT content.id AS id FROM prm20_easyblog_post AS content WHERE content.published = 1 AND content.private = 0 AND ( content.publish_up = '0000-00-00 00:00:00' OR content.publish_up <= '2015-06-19 02:01:13' ) AND ( content.publish_down = '0000-00-00 00:00:00' OR content.publish_down >= '2015-06-19 02:01:13' ) AND ( content.category_id = 3 ) ORDER BY content.created DESC LIMIT 0,1;

**Comment by dziudek** [comment]
Hello,

We will add a support for EasyBlog in the next update.
