### ISSUE TITLE
Why are article names from NSP GK5 showing up incorrectly in breadcrumbs? 

### ISSUE THREAD

**Issue by JoePiscapo** [GavickPro/News-Show-Pro-GK5#296]
Hey man,

When I click on an article from NSP GK5, the name shows up correctly in the breadcrumbs.  But then the next ones that I click on, the breadcrumbs just keep displaying the first article name that I had clicked on.  And this continues until I clear the cache. 
I have the NSP GK5 module set up with a menu item in the hidden menu and a category setup, all the articles fall under the same category.  

Can you advise? Thanks!

**Comment by dziudek** [comment]
Hello,

I suppose that your issue is not connected with our module, but with your joomla config or directly with the breadcrumbs module.
