### ISSUE TITLE
Can I get comments for articles in Joomla 3.4.1?

### ISSUE THREAD

**Issue by JoePiscapo** [GavickPro/News-Show-Pro-GK5#297]
Hey Tomasz,

We've updated to Joomla 3.4 and I'd really love to have comments available for articles, hopefully in NSP GK5. Can I get that?

Thanks for all your help by the way.

Mike

**Comment by dziudek** [comment]
Hello,

Our module is designed to display articles not for adding comments - please use JComments or Komento for it.

**Comment by JoePiscapo** [comment]
Ok great thanks!
