### ISSUE TITLE
Comment style modifications!

### ISSUE THREAD

**Issue by sirdna** [GavickPro/News-Show-Pro-GK5#299]
Hello!

We would like to change comment style on our news show pro gk5 module

We have "2 (apspriest)" We would like to have Apspriest (2) (apspriest menas comment or disucss)

To get the idea I have attached an image to visualize

Basicly we need to put comments in brackes and switch palces, first is "Apsrpiest" than comments count, seems eas
(brakcet with apspriest i get changing the language file lv-LV.mod_news_pro_gk5 its no problem without brackes)

As i undestand we have to change something there:
in the mod_news_pro_gk5/tmpl/com_content/view.php file (or mod_news_pro_gk5/tmpl/com_k2/view.php

probably there
 	$info_comments = JText::_('MOD_NEWS_PRO_GK5_NO_COMMENTS');
		        //
		        if(isset($item['comments'])) { 
		        	if($item['comments'] == 1) {
		            	$info_comments = JText::_('MOD_NEWS_PRO_GK5_1COMMENT');
		            } else if($item['comments'] > 1 && $item['comments'] < 5) {
		            	$info_comments = $item['comments'] . ' ' . JText::_('MOD_NEWS_PRO_GK5_MORECOMMENTS');
		            } else if($item['comments'] >= 5) {
		            	$info_comments = $item['comments'] . ' ' . JText::_('MOD_NEWS_PRO_GK5_MUCHMORECOMMENTS');
		            }
		        }

Try to do it by myself but it dont worked for me, somehow we need swithch places un put comments in brackets

Can you please help me..?

![apspriest](https://cloud.githubusercontent.com/assets/11191907/8438047/0e3afe00-1f6c-11e5-9c63-fb6aae608d96.png)

**Comment by dziudek** [comment]
Hello,

You should first of all check the language file for the phrases used in the mentioned code fragments - because the text "(apspriest)" doesn't exists in our files so you probably have a translation where word "comments" is replaced with "(apspriest)".

Regarding the code fragment - you have to revert the order of code i.e.:

```php
JText::('MOD_NEWS_PRO_GK5_MUCHMORECOMMENTS') . ' ' . $item['comments'] 
```

to:

```php
JText::('MOD_NEWS_PRO_GK5_MUCHMORECOMMENTS') . ' ' . $item['comments']
```

You can also wrap $item['comments'] into brackets.

**Comment by sirdna** [comment]
Thank you! Worked for me!
