### ISSUE TITLE
Fatal error: Class 'VmConfig' not found in /var/www/html/modules/mod_news_pro_gk5/tmpl/portal_modes/product_gallery_2/controller.php on line 40

### ISSUE THREAD

**Issue by alexcywu** [GavickPro/News-Show-Pro-GK5#300]
Fatal error: Class 'VmConfig' not found in /var/www/html/modules/mod_news_pro_gk5/tmpl/portal_modes/product_gallery_2/controller.php on line 40

**Comment by dziudek** [comment]
Hello,

Please change button type from cart in the portal mode additional settings tab.
