### ISSUE TITLE
Multilingual site dutch and English

### ISSUE THREAD

**Issue by Joomron** [GavickPro/News-Show-Pro-GK5#303]
Hey,

I want to use two times News Show Pro GK5 on a joomla site.

One Dutch and the other for English I use module mode Portfolio Grid.

On the Dutch site works well (www.mysite.nl/afbeeldingen) 

The English site works not because there is EN (www.mysite.nl/en/images-gallery)in the url.
You will only see the icon from loading the images.

When I turn off url rewrite module works well in English.

Example:
www.mysite.nl/afbeeldingen works good!
www.mysite.nl/nl/afbeeldingen works not. Problem is NL code
www.mysite.nl/en/images works not. Problem is EN code

Anyway, I put the module in Mainbody.

Where can lay this problem?

Thanks in advance.

greetings Ron

**Comment by dziudek** [comment]
Please provide me a working URL to your website.

**Comment by Joomron** [comment]
Hello,

url is http://www.bartelart.nl/ on left site you have menu.

http://www.bartelart.nl/verkrijgbare-prints Dutch is working.
http://www.bartelart.nl/en/available-prints English is not working.

Greatings Ron

**Comment by dziudek** [comment]
Sorry but your page is offline

**Comment by Joomron** [comment]
Hello Dziudek,

the website is online now.

Greatings Ron

**Comment by dziudek** [comment]
Please try to apply this patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/89948508db4fd270f79e7a91fd9b5c3d5da61624

**Comment by Joomron** [comment]
Hello,

the patch is not working.

I have code adjusted manually and downloaded the entire php code and upload this with ftp.

Both solutions are not working. Do you have other suggestions?

Greatings Ron

**Comment by dziudek** [comment]
Please send me a mail with FTP access to your website: dziudek[at]gavick[dot]com

**Comment by Joomron** [comment]
I send you a mail 

Thanks in advance for the effort.

Greatings Ron

**Comment by dziudek** [comment]
Problem solved - the fix was correct, but you had a NSP GK5 override in the template (in the html directory) what caused that your change was not visible in the output code :)

**Comment by Joomron** [comment]
Sorry for the late respons but thanks for your help!
Greatings Ron
