### ISSUE TITLE
News Pro GK5 xml data source customization

### ISSUE THREAD

**Issue by spotview** [GavickPro/News-Show-Pro-GK5#305]
Hello,
I'm asking for a News Pro GK5 module customization that allows to load a custom xml file (with custom tags) with the possibility to change on occurrence the custom tags loaded by the extension (via module panel or also via code).

I need also that every value in xml file is loaded on front end inside a div with a css class of the same name to graphically customize them.

thanks in advance...

**Comment by dziudek** [comment]
Hello,

Unfortunately currently we are too busy for providing any custom works for the NSP GK5 module.
