### ISSUE TITLE
 'lines'  as additional option for text limit in article layout (header and text)

### ISSUE THREAD

**Issue by gitEdMax** [GavickPro/News-Show-Pro-GK5#307]
Hi,

While enjoying the News-Show-Pro-GK5 tool, we came up an idea for an enhancement with an additional option to set the text limit for header and text in the article design.

Next to the number of words or characters, the number of ‘lines’ would be a nice addition.
This would result in an even length of the presented items.

Especially while used in responsive templates, the number of words and characters is a bit ‘vague’, resulting in different length of the descriptions for the shown articles. 

The number of lines could result in a fixed length for each article, offering a bit nicer presentation.

Thanks for all the good work!
Ed

**Comment by dziudek** [comment]
Sorry but this kind of feature is almost impossible to implement - the only way is calculate the line-height and then use overflow hidden for it, but then it will cause creating text which is finished without any visual ending like "...".

**Comment by gitEdMax** [comment]
Hi Tomasz,

 

Thanks for your thoughts. 

You might have worked out the ‘routine’ as highlight in your reply…

 

I would say that the missing ‘….’ at the end is less important while the ‘Read more’ feature is sort of explaining the interruption of the text in that situation.

 

In case you find a moment for this challenge we are your supporter!

 

All the best!

Ed

 

 

Van: Tomasz Dziuda [mailto:notifications@github.com] 
Verzonden: woensdag 16 september 2015 16:54
Aan: GavickPro/News-Show-Pro-GK5
CC: Ed
Onderwerp: Re: [News-Show-Pro-GK5] 'lines' as additional option for text limit in article layout (header and text) (#307)

 

Sorry but this kind of feature is almost impossible to implement - the only way is calculate the line-height and then use overflow hidden for it, but then it will cause creating text which is finished without any visual ending like "...".

**Comment by gitEdMax** [comment]
Hi Tomasz,

 

To illustrate the request, I attached a screenprint.

 

Have a nice day!

Edger

 

Van: Tomasz Dziuda [mailto:notifications@github.com] 
Verzonden: woensdag 16 september 2015 16:54
Aan: GavickPro/News-Show-Pro-GK5
CC: Ed
Onderwerp: Re: [News-Show-Pro-GK5] 'lines' as additional option for text limit in article layout (header and text) (#307)

 

Sorry but this kind of feature is almost impossible to implement - the only way is calculate the line-height and then use overflow hidden for it, but then it will cause creating text which is finished without any visual ending like "...".
