### ISSUE TITLE
Formatting text em Grid News

### ISSUE THREAD

**Issue by kewwel** [GavickPro/News-Show-Pro-GK5#310]
Hello, I'm using Grid News layout. I wanted to know how to prevent the module break formatting. Example: I need what module to take the  text the way it is in the item of the article. 
I just need to display two text lines, one beneath the other and under an external link. 
The module only need not break that formatting. Already well I inspected the Controller.php but with no success. Can you help me?
![modulo](https://cloud.githubusercontent.com/assets/4606218/10266146/537594f8-6a26-11e5-8d4f-bf868db2af9f.jpg)

**Comment by dziudek** [comment]
Hello,

Probably your issue is connected with this line: https://github.com/GavickPro/News-Show-Pro-GK5/blob/J!3.0_compatible/mod_news_pro_gk5/tmpl/portal_modes/grid_news/controller.php#L70

Unfortunately there is no easy way to cut text with HTML tags inside.
