### ISSUE TITLE
Where can get the Gk5 2014?

### ISSUE THREAD

**Issue by adriannx** [GavickPro/News-Show-Pro-GK5#311]
Hello,

Where can get the Gk5 2014? i wanna this version cuz i'm using easyblog 3.9

Regards!

**Comment by dziudek** [comment]
Hello,

Please check this list: https://github.com/GavickPro/News-Show-Pro-GK5/commits/J!3.0_compatible - you can come back to any moment of the module development and then download the full package from the specific moment :)

**Comment by adriannx** [comment]
Hello,

Thank you!
