### ISSUE TITLE
NSP is showing trashed articles from EasyBlog

### ISSUE THREAD

**Issue by teitbite** [GavickPro/News-Show-Pro-GK5#312]
/data_sources/com_easyblog/model.php file line 264

under line

"content.published = 1"

add a new line

"AND content.state = 0"

**Comment by dziudek** [comment]
Dodane: https://github.com/GavickPro/News-Show-Pro-GK5/commit/80620a0f3e317e84c0ba21878f0c8c631e0c46c3 wydam z kolejnym update.
