### ISSUE TITLE
VirtueMart ordering.

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/News-Show-Pro-GK5#313]
In datasource "News order" can be set to "By order" which works well with default Joomla articles bu doesn't work with manual ordering of VM products. Shouldn't it work same way?
(Joomla articles has "Ordering" column which is used to set order but VM doesn't).

**Comment by dziudek** [comment]
Please try to use this fix: https://github.com/GavickPro/News-Show-Pro-GK5/commit/b93fbd739cb967cc68020942844089dfde1e5a09
