### ISSUE TITLE
Featured article image and description not displayed

### ISSUE THREAD

**Issue by adriannx** [GavickPro/News-Show-Pro-GK5#316]
Hello Tomasz Dziuda, 

When I highlight an item, this is not displayed correctly.
The image and description is not displayed. Am i doing something wrong? I'm using easyblog 5

![featured-issue-image](https://cloud.githubusercontent.com/assets/5619504/10712817/7fdabd3a-7a6a-11e5-90dc-58b4d7225411.PNG)

Best Regards!

**Comment by dziudek** [comment]
Hello,

Could you provide an URL to your website? And send me an email to dziudek[at]gavick[dot]com with the access data to your back-end?

**Comment by adriannx** [comment]
Hello Tomasz Dziuda, thanks for reply

I just sent my data.

Best Regards!

**Comment by dziudek** [comment]
I see that now your issue disappeared - did you changed something? Your article was not planned article?

**Comment by adriannx** [comment]
is not disappeared, try featured an blog/article..

Regards!

**Comment by dziudek** [comment]
Ok, now I see it - I've applied the following patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/1776b1615399d7af88bd1b538c023ec90d8c1049 it fixes the issue with images.

Regarding the text - you have to create an intro text in your articles without it the text is not displayed.

**Comment by adriannx** [comment]
Hello dziudek,
But I do not use the line intro text. As you can see, previously it worked correctly, but that has not happened after. Intro text should work automatically.
![559](https://cloud.githubusercontent.com/assets/5619504/10763828/77021646-7c99-11e5-910c-da25d464c06d.PNG)

Regards!

**Comment by dziudek** [comment]
The intro column in your new articles is empty but in the previous one is not empty - so it must be something with your article structure.

**Comment by adriannx** [comment]
Can I do something for that stackideas solve this? since I have previously used  EasyBlog 3.9 and not had these issue.

Regards!

**Comment by dziudek** [comment]
So it seems that older articles are in other format than the new ones.

I've prepared a solution for it which is also now implemented on your page:

https://github.com/GavickPro/News-Show-Pro-GK5/commit/65e108f483ce1ee5e1d430d82f24387efb5b7d4b

https://github.com/GavickPro/News-Show-Pro-GK5/commit/c2fb96171700481c107907ecd96388fc32ac0bac

**Comment by adriannx** [comment]
Hello dziudek,

Thanks, I appreciate the great job you are doing.

Now gk5 is working properly. Do you will update  the module Gk5  so that in the future there will be no such problems?

Best Regards!

**Comment by dziudek** [comment]
All mentioned fixes will be included in the next update.

**Comment by adriannx** [comment]
That's Great!

Regards!
