### ISSUE TITLE
How override module files ?

### ISSUE THREAD

**Issue by houbahoubi** [GavickPro/News-Show-Pro-GK5#318]
Hello
I try to override the file : /modules/mod_news_pro_gk5/tmpl/view.php to change the h4 tags in my convinience.
So I copy the file in /templates/mytemplate/html/mod_news_pro_gk5/tmpl/ or without /tmpl
but the override doesn't works.
Can you help me please ?
Thanks

**Comment by dziudek** [comment]
Hello,

The /templates/mytemplate/html/mod_news_pro_gk5/view.php file should override the view.php file from our module.

Did you cleaned up your joomla and browser cache after the changes?

**Comment by houbahoubi** [comment]
Hello
Yes I cleaned up in joomla and CTRL+Shift+Suppr form the browser.
But there is no change

**Comment by dziudek** [comment]
Please send me your page url and ftp access to dziudek[at]gavick[dot]com

**Comment by dziudek** [comment]
I've applied the following fix: https://github.com/GavickPro/News-Show-Pro-GK5/commit/22cd82c5712125ab906d583665e85dc02887041a and also I've created new override directory, because your old one was broken (I cannot delete it, so I've renamed it). Problem is solved now.

**Comment by houbahoubi** [comment]
Well done. Thanks for your help

**Comment by houbahoubi** [comment]
Hello
Me again
I have updated the module News-Show-Pro-GK5 and the problem come again !
The override is not applied.
Have you an idea
