### ISSUE TITLE
Updating NSP GK5 to v 1.9.2.1 produces error

### ISSUE THREAD

**Issue by MarRose** [GavickPro/News-Show-Pro-GK5#321]
I have NSP GK5 which came as part of a Joomla template from zootemplate.com which was working fine until I updated it recently to the latest version 1.9.2.1. Now I get the errors: Notice: Undefined variable: item in ... \modules\mod_news_pro_gk5\tmpl\view.php on line 341 and line 344. These two error are repeated for the number of items that will be displayed in the module. The first few items are displayed after the list of errors but they are static. Please help as I have limited knowledge of programming.

**Comment by dziudek** [comment]
Hello,

In the newest version available on the repository the issue should not exist: https://github.com/GavickPro/News-Show-Pro-GK5/archive/J!3.0_compatible.zip

**Comment by MarRose** [comment]
Hi,
Thanks for that but though I no longer get the errors, the animation is still not working.

**Comment by dziudek** [comment]
@MarRose - please provide an URL to your website with this issue.

**Comment by MarRose** [comment]
This is a site under development on my local server so I cannot give you access. I'll go back to the previous version of NSP GK5 as this worked fine and ignore the messages to update.

**Comment by MarRose** [comment]
I've just found the cause of the problem! It was a module 'zt-slideshow' that came with a template from zootemplate.com that for some reason stopped the animation of the latest version of NSP GK5. I switched to another slideshow module (which I was going to do anyway) and now NSP GK5 animates fine.
