### ISSUE TITLE
After updating News-Show-Pro-GK5 my overrides doen't work anymore

### ISSUE THREAD

**Issue by houbahoubi** [GavickPro/News-Show-Pro-GK5#322]
Hello
I just see that the issue here : https://github.com/GavickPro/News-Show-Pro-GK5/issues/318 is closed but I can write comments (curious?).
So I open a new issue because the problem come again after updating the module.
Have you an idea ?
Thanks

**Comment by dziudek** [comment]
My fix is not working, because version with this fix was not released yet. Please apply my fix manually: https://github.com/GavickPro/News-Show-Pro-GK5/commit/22cd82c5712125ab906d583665e85dc02887041a

**Comment by houbahoubi** [comment]
ok it works. I hope the fix will be in the next release.
Thanks
