### ISSUE TITLE
mod_news_pro_gk5/tmpl/view.php overide.

### ISSUE THREAD

**Issue by Cyberek** [GavickPro/News-Show-Pro-GK5#324]
Seems like more and more users would like to overide this file with use of template overides. Sadly it cannot be done this way. Maybe we could somehow modify the way view files are so any of them can be changed (without changing module files).

(https://www.gavick.com/forums/news-show-pro/nsp-gk5-thumbnails-are-unsharp-after-mouseover-49149?p=247481#p247481)

**Comment by dziudek** [comment]
You can suggest our users to install this version: https://github.com/GavickPro/News-Show-Pro-GK5/releases/tag/v.1.9.3-alpha it contains a fix for this issue.
