### ISSUE TITLE
I can not download News Show Pro GK5 from your website

### ISSUE THREAD

**Issue by baijianpeng** [GavickPro/News-Show-Pro-GK5#326]
hi, today I went to your website to download this module, the page URL I enter is:

https://www.gavick.com/download/joomla-modules/newshowpro

And after I click on the last download link ( mod_news_pro_gk5_J!3.zip ) , it returns some XML error, instead of a zip file.

Could you please fix that broken link or offer a download button on GitHub for this module?

Thank you.

**Comment by dziudek** [comment]
Hello,

Most probably your download link expired - please try to download the file directly after opening the download website.

**Comment by baijianpeng** [comment]
It is NOT my download link, I just opened your website (the URL I had
mentioned above) , and click on that download link on YOUR webpage, and
then the page returned ERROR.

What is wrong?

2015-12-07 13:26 GMT+08:00 Tomasz Dziuda <notifications@github.com>:

**Comment by dziudek** [comment]
Sorry but for me the link is working fine - I've tried it 2 hours ago and now - it is downloading the package correctly. If you are still unable to download the file - please download packages from here: https://github.com/GavickPro/News-Show-Pro-GK5/releases

**Comment by baijianpeng** [comment]
Yes, this is the link I want to click.

Thank you, your Github link let me get the latest version.

baijianpeng

2015-12-07 15:36 GMT+08:00 Tomasz Dziuda <notifications@github.com>:
