### ISSUE TITLE
Source of articles: Virtuemart Product only show the first image

### ISSUE THREAD

**Issue by santo1227** [GavickPro/News-Show-Pro-GK5#332]
Hi,

The module only show the firts image

Module mode: Standard mode
Article Layout >
Amount of pages with arts: 4
Amount of columns: 4
Amount of rows: 4

What can it be?

![preview](https://cloud.githubusercontent.com/assets/643403/11876126/0e4cc642-a4b6-11e5-9264-e94e1ccd820d.jpg)

Thanks in advance and regards

**Comment by dziudek** [comment]
Hello,

Could you provide an URL to your website?

**Comment by santo1227** [comment]
Sure,

http://sarobu.com/cibao/index.php

**Comment by dziudek** [comment]
Please send me your back-end and FTP access to dziudek[at]gmail[dot]com - your issue will need a deeper analyze.

**Comment by santo1227** [comment]
Hi Tomasz

I have sent the info

Regards

**Comment by dziudek** [comment]
I've applied the following patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/225edcbdd4c3d570a4e14d197f924ff6e6e11ce0 and now images are working fine on your page :)

**Comment by santo1227** [comment]
Thank you very much Tomasz :),

It's an excelent module 

Regards
