### ISSUE TITLE
Changing Article Title from h4 to h1 or h2 in News Show Pro GK5

### ISSUE THREAD

**Issue by shigri20** [GavickPro/News-Show-Pro-GK5#333]
how can i change Article Header from h4 to h1 or h2.
actually i want to have all h1,h2 ,h3 and h4 tags in home page .  i assigned Header Tag h2 from Advanced tab but how can i change Article title heading tag?

**Comment by dziudek** [comment]
Hello,

The only way is changing the output in this function: https://github.com/GavickPro/News-Show-Pro-GK5/blob/master/mod_news_pro_gk5/tmpl/view.php#L18

**Comment by shigri20** [comment]
thanks

**Comment by shigri20** [comment]
thank-you for good response.
i have another question .. in front-end a lot of module (gk5) are available that assigned h2 tag through changing in view.php file ... Now i  have one feature News that i want to assigning H1. is there any solution?

**Comment by dziudek** [comment]
@shigri20 - sorry, but it needs a more complex custom work which is beyond of our technical support.

**Comment by shigri20** [comment]
@dziudek  ok thanks. i just want to suggest that can be helpfull in seo  by adding this option in module .
