### ISSUE TITLE
Sopport Image show gk4?

### ISSUE THREAD

**Issue by adriannx** [GavickPro/News-Show-Pro-GK5#334]
Hello Tomasz Dziuda,

It also gives support to the extension "Image Show GK4"?

Best Regards!

**Comment by dziudek** [comment]
Issues for Image Show GK4 are available here: https://github.com/GavickPro/Image-Show/issues

Please remember that support on Github is limited to a issues with module code - it doesn't contain custom changes - for it please contact i.e. with http://tidycustoms.net/

**Comment by adriannx** [comment]
ok thank you

Regards!
