### ISSUE TITLE
News-Show-Pro-GK5 disappeared from the home page

### ISSUE THREAD

**Issue by Diversesolution** [GavickPro/News-Show-Pro-GK5#335]
Hi ,

all  Gk5 pro modules have disappeared from the home page. I thought it was due to the fact that isn´t update. After i did the update it remains the same as you can see : http://www.lostrappoquotidiano.it/

Can you help me out with this please ? 

Regards,
Luigi

**Comment by dziudek** [comment]
Hello,

Please consult your issue with your template developer - modules are hidden by ```hidden-sm hidden-md hidden-lg``` CSS classes set in the module suffixes.

**Comment by Diversesolution** [comment]
Hi ,
it is me that i settled those css classes , but they are there since always and the module was working fine. Those css apply for different devices screen. It has nothing to do with the fact that gk5 does not appear on the home page. I did an extra test and the problem is stil there

**Comment by dziudek** [comment]
When I have removed these CSS classes both hidden modules are appearing correctly: https://www.evernote.com/l/AKWg2dBwBRxIzaAC1GjGOviudczJr3x7BmUB/image.png

**Comment by Diversesolution** [comment]
You have removed the hidden-lg from a module that was published for the mobile version. But if i create a new module without class and i publish in the home it does not appear. So this test make me think that can not be the css class. Must be something missing after the update or before.

**Comment by dziudek** [comment]
Please consult this issue with your template developer - in my opinion this issue is not related to our module.

**Comment by Diversesolution** [comment]
I am trying to understand , the module has been working fine here http://thelundian.com/ i have the same module and the same template layout and it is working fine, on this website i did not update your module. That is why i am wondering.

**Comment by Diversesolution** [comment]
Now i can see the problem. It is the layout , the modules where gk5 is published are disappeared from the home page!
