### ISSUE TITLE
Problem with x number of modules on same page

### ISSUE THREAD

**Issue by kortex123** [GavickPro/News-Show-Pro-GK5#338]
Hi there,
I'm using your module for creating article blocks on a new interface of a news website. I'm using two kind of module modes: 
**Portofolio Grid with these settings:**
- Source of articles: Joomla! categories
- News order: by date
- News sort order: descending
- First news number: 0
- Show article created after: none
- Show article created in last X days: none
- Show featured items: yes
- Featured items only: yes
- Show unauthorized items: off
- Time offset: -2

**Standard mode with these settings:**
- Source of articles: Joomla! categories with one category selected
- News order: by date
- News sort order: descending
- First news number:  from 1 to x, 
- Show article created after: none
- Show article created in last X days: none
- Show featured items: yes
- Featured items only: no
- Show unauthorized items: off
- Time offset: -2

On the front page, i have one Portofolio grid module and about 73 Standard mode modules. Here, the problem is that it takes a long time to render the html because the module scans the entire _content table with about 65000 articles, even if the script is ment to scan just the non-archived articles.

On the other pages, i have about 15 Standard mode modules. Here, the problem is that i get a "Fatal error: Allowed memory size of 134217728.............in /home/.........../libraries/joomla/database/driver/mysqli.php on line 796" when the amount of non-archived articles from a specific section is smaller than the module first news number, which is logical. 
My question would be how to limit the article database lookup to arround 500 rows maximum, for a better page render time?
I have found this in the /data_sources/com_content/model.php file on line 62:

$query_name = '
				SELECT 
					c.id AS CID
				FROM 
					#__categories AS c
				LEFT JOIN 
					#__content AS content 
					ON 
					c.id = content.catid 
					'.$tag_join.'	
				WHERE 
					1=1 
					'.$where.'
					AND 
					c.extension = '.$db->quote('com_content').
					$tag_where.
					' AND 
					c.published = 1
		        ';	
If i put LIMIT 500 after c.published=1, it works, but only on modules from the first page.

**Comment by dziudek** [comment]
Sorry but with this number of modules and this amount of articles there is no way to run the page with memory limit set to 128MB. And limiting the queries won't help as it can provide incorrect results.

**Comment by kortex123** [comment]
Thank you for your response. But if I'll use just a few modules with the same amount of articles?

**Comment by dziudek** [comment]
It also can be a problem - you have to test this case.

**Comment by kortex123** [comment]
Thanks again. Now, i'm trying to use just the default jooma blog layout to do what i want. It loads very quickly, but it doesn't have same facilities as your gavick module. I was wondering if there would be a solution to call in the database query once per page for all the modules, if they have the same article source. My problem is that, beside those news modules, i want to load some modul position with ads in them. That's why i decided to use gavick news pro gk5. 

Ciprian

Trimis de pe iPhone-ul meu

Pe 19 feb. 2016, la 14:59, Tomasz Dziuda <notifications@github.com> a scris:

**Comment by dziudek** [comment]
Sorry but your questions are definitely outside of our technical support here.
