### ISSUE TITLE
Undefined indexes

### ISSUE THREAD

**Issue by thekrotek** [GavickPro/News-Show-Pro-GK5#342]
Updated NSP GK5 recently and again hit the same issues with undefined indexes:

 ```
Notice: Undefined index: nsp_pre_text in /modules/mod_news_pro_gk5/tmpl/default.php on line 27

Notice: Undefined index: nsp_post_text in /modules/mod_news_pro_gk5/tmpl/default.php on line 165
```
This isn't the first time, when I see this message with pre_text and post_text values after update, because I never add any pre or post text.

Just add a check for this indexes once and for all. Easy to do.

**Comment by dziudek** [comment]
Hello,

Did you tried to resave the module settings?

**Comment by thekrotek** [comment]
Huh, indeed it worked after saving. Yet I prefer to code with checks by empty() function to avoid such issues. But that's for you to decide, of course.
