### ISSUE TITLE
News 2 template

### ISSUE THREAD

**Issue by malakAngela** [GavickPro/News-Show-Pro-GK5#343]
Hi, I have some questions about News 2 template:
1 - How to make all links in my article open in new window (because I have put a mindmap in my article and I need that links open in new window not in the parent)
2 - SlideShare is disabled for mobile devices in the template css, Where and how can I enable it?
3 - How to redirect the user after login to the home page, I have put it but it does not work!
4 - How to make all the template in french (read more,...)?

Please if you can help me!
Thanks in advance,

Best regards!

**Comment by dziudek** [comment]
Please use an official forum as it is a paid product. https://www.gavick.com/forums
