### ISSUE TITLE
k2 extra field display not working after update

### ISSUE THREAD

**Issue by kaeau** [GavickPro/News-Show-Pro-GK5#345]
hi,
after a regular update to the new version, the K2 extra fields in the NSPGK5 Module with a custom artcile format file does not work anymore.

the extrafields are included in the .format file with their alias, e.g.: <div class="testimonial name">{{testimonialname}}</div>

in the frontend, the output is just "{{testimonialname}}", not the extrafield content anymore.
best regards,
ka

**Comment by dziudek** [comment]
Hello,

Please try to check if reverting these changes helps: https://github.com/GavickPro/News-Show-Pro-GK5/commit/a2d7321b5a640fd6af82ced2588b49c8b99926db

**Comment by kaeau** [comment]
thanks! that helped,
works again.
best regards!
ka
