### ISSUE TITLE
modue.php.suspected ?!

### ISSUE THREAD

**Issue by mrfouad2000** [GavickPro/News-Show-Pro-GK5#346]
HI, recently my site went down 

the problem was this file changed 
/modules/mod_news_pro_gk5/data_sources/com_k2/model.php
into 
/modules/mod_news_pro_gk5/data_sources/com_k2/model.php.suspected 

any ideas ?!

**Comment by dziudek** [comment]
Hello,

Most probably AV software on your hosting found some suspicious code in the mentioned file or it is false positive. Please compare this file with the one from the repository and rename it if it is clean.

**Comment by mrfouad2000** [comment]
Thank you for your Answer, i will try it

**Comment by dziudek** [comment]
Hi again,

We had reported a security issue which was connected with the mentioned file (and two other ones). Please upgrade your NSP to v.1.9.3.4 which has been just released.

**Comment by mrfouad2000** [comment]
Thank you Dziudek for your Answer 
i upgraded the plugin and every thing is going well now :) 

Thank you
