### ISSUE TITLE
How to display more news

### ISSUE THREAD

**Issue by raunhar** [GavickPro/News-Show-Pro-GK5#347]
I have installed this extn on a school web site, to display the notice that the school issues every now and then.
In all there will be around 9 news articles.
I have selected the Option: Highlights, and under portal node settings, the amount is 5. If I set it to 9, then the module height increases.

Is there any way that the article headings, scroll down to up or vice versa.
The URL is: http://www.sgnps.in/modi

The module is next to the slide show.

**Comment by dziudek** [comment]
Hello,

Sorry but this portal mode has no scroll option - implementing it is a custom work beyond of our technical support here.

**Comment by raunhar** [comment]
Thanks.
One more query.
When the viewer clicks on the news, it is opening on the same page.
Is it possible that it opens in a new page.
http://www.sgnps.in/modi/

The slideshow and other modues are enabled for home page only.

**Comment by dziudek** [comment]
Most probably you have an issue with your links structure and the posts are displayed on the frontpage. Please create menu items for your post categories.
