### ISSUE TITLE
Problems with News Shop Pro GK5 update (Joomla 3.5.0)

### ISSUE THREAD

**Issue by zonaweb** [GavickPro/News-Show-Pro-GK5#348]
Hello all,
I've just uddated to the las version of Joomla 3.5.0. After that I checked that my website worked OK.
After that I updated the extensions versions. After updating News Shop Pro GK5 my website cracked. 
It appeared an error message 1054 "It appears the page you were looking for doesn't exist. Sorry about that."
I verified it was the News Shop Pro GK5 plug-in because this erroed dissapears if I disable it on the Joomla Extension Manager.
Of course without News Shop Pro GK5 working my website lhomepage lose features, and I want to restore News Shop Pro GK5 functionallity again.

My website is created on the MeetGavern template.

Please could you help me to fix this problem?

Than you very much in advance.

**Comment by dziudek** [comment]
Please download and install this file: https://github.com/GavickPro/News-Show-Pro-GK5/releases/tag/v.1.9.3.3

**Comment by zonaweb** [comment]
Thank you very much.

Regards.
