### ISSUE TITLE
New Layout mode

### ISSUE THREAD

**Issue by ismaelhaider** [GavickPro/News-Show-Pro-GK5#350]
Hello Folks,

I am trying to create new mode for testing, here is the steps which i am following

- I went /modules/mod_news_pro_gk5/tmpl/portal_modes  and tried to clone mode"news block" as **news block copy**.
- When I back into backend setting of module, Basic setting tab then module mode- its not showing me my clone mode which is "**news block copy**"

How we can create any new mode ?

**Comment by dziudek** [comment]
Hello,

Please remember that you should also edit the **configuration.json** file inside your copy of the portal mode. It is used to retrieve the list of portal modes:
https://github.com/GavickPro/News-Show-Pro-GK5/blob/master/mod_news_pro_gk5/admin/elements/portalmodes.php

**Comment by ismaelhaider** [comment]
Hi folks,

Thanks for quick reply, I edited **configuration.json** file
`{
	"name": "News_Blocks_copy",
	"full_name": "NEWS_BLOCKS_COPY",
	"support": [
		"com_content", 
		"com_k2",
		"com_easyblog",
		"com_virtuemart"
	],
	"thumbnails": true
}`

When I check it from backend,it shows me mode, but its showing with name **MOD_NEWS_PRO_GK5_NEWS_BLOCK_COPY**  I dont know why it ads additional name **MOD_NEWS_PRO_GK5_**

**Comment by dziudek** [comment]
You have to prepare a language phrase in the language file for your portal mode as the portal modes can have a different names under different languages.

Regarding the standard mode - it is not in the portal_modes directory as in fact it is not a portal mode :) It uses **tmpl/default.php** and **tmpl/view.php** files

**Comment by ismaelhaider** [comment]
Thanks, I am playing with GK News Pro 5 modules, It has alot of features in backend. In Standard mode,there is links section also, Links are published, We are unable to Show **Information **for these links like **Category**,**Comments**, **Dates **.

Can you Add these features in links section.or is there any way to add these things .Appreciate if you can assist me,

**Comment by dziudek** [comment]
The idea of links is to display only basic informations - this is the difference between articles and links and we have no plans to add more options for links currently.

**Comment by ismaelhaider** [comment]
Thanks for excellent module development
