### ISSUE TITLE
Info format for Category

### ISSUE THREAD

**Issue by ismaelhaider** [GavickPro/News-Show-Pro-GK5#351]
Hi team,

I am using portal mode.I want to move Category title above the image.I am not able locate the code where to change info format.Can you tell me the file and code line#, also check the screenshot 
<blockquote class="imgur-embed-pub" lang="en" data-id="2fNWUpk"><a href="//imgur.com/2fNWUpk">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
http://imgur.com/2fNWUpk

**Comment by dziudek** [comment]
For me this will be possible only with a custom JS script which will move the category element into image frame.

**Comment by ismaelhaider** [comment]
hhmm Thanks for hint.
