### ISSUE TITLE
Slow query ISSUE

### ISSUE THREAD

**Issue by klausveliu** [GavickPro/News-Show-Pro-GK5#352]
Hello,
We are using News Show Pro GK5. 
I must say its a wonderful module from its features, so many features in one module...

My issue its very serious!!! 
This module content its being cached by Joomla,
but when many articles are added to often the cache its cleaned and regenerated.
In this moment the modules generates slow queries causing my website(www.newsbomb.al) to crash.

SELECT DISTINCT i.*, g.title AS groupname, c.name AS category, v.name AS author, w.name as moderator, u.name AS editor FROM p38xt_k2_items as i LEFT JOIN p38xt_k2_categories AS c ON c.id = i.catid LEFT JOIN p38xt_viewlevels AS g ON g.id = i.access LEFT JOIN p38xt_users AS u ON u.id = i.checked_out LEFT JOIN p38xt_users AS v ON v.id = i.created_by LEFT JOIN p38xt_users AS w ON w.id = i.modified_by WHERE i.trash=0 ORDER BY i.id DESC LIMIT 0, 50;

My feed its just the image, title, create date, introtext of latest articles,
Could your help me how to fix this issue?!

![screenshot_2](https://cloud.githubusercontent.com/assets/6373413/14505647/5f34a294-01ba-11e6-8301-e929aa1ea2a3.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/6373413/14505570/0234b1e2-01ba-11e6-9d43-052c13d9c93c.png)

**Comment by dziudek** [comment]
Hello,

In my opinion this query is not from our module - we have removed queries with distinct for k2 a long time ago and I cannot find this query in our module.

**Comment by klausveliu** [comment]
Sorry maybe I have bothered you.
When I tested the query in phpmyadmin the result was that of the latest articles...

Just your comment(we have removed queries with distinct for k2) make me say "Eureka",
I searched all the php modules content and found that "Ugly BT Content Slider" was causing that!

Thank you for the support!
Keep going with your great work (Y)
