### ISSUE TITLE
GK5 & com_ajax

### ISSUE THREAD

**Issue by aaron-harding** [GavickPro/News-Show-Pro-GK5#361]
On a recent project, I have a simple bookmarks module which makes use of com_ajax to bookmark a page through an ajax request.

When installing and enabling GK5, these requests are broken with the following error:

> Fatal error:  Call to undefined method JDocumentJson::getHeadData() in <b>/home/***/modules/mod_news_pro_gk5/helper.php on line 215

/modules/mod_news_pro_gk5/helper.php: Line 215
`$headData = $document->getHeadData();`

$document in the context of com_ajax is an instance of JDocumentJson where the getHeadData method is not defined. Before calling the getHeadData this should check that $document is an instance of JDocumentHtml.

**Comment by dziudek** [comment]
Hello,

Please try to apply this patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/39cb7094195a7ff45edeeb1dccde5aafae1a50b7

**Comment by aaron-harding** [comment]
Hi,

That patch fixed the issue.
