### ISSUE TITLE
Images not displaying in TechNews portal modes

### ISSUE THREAD

**Issue by army113** [GavickPro/News-Show-Pro-GK5#363]
With https turned on for the whole site the background image of an article is displayed like this:
background-image: url('https://xyz.com/https://xyz.com/media/k2/items/cache/bc61c35998920c79a57e03ad91265e8b_Generic.jpg');
The get_image function in controller.php only checks for http in the url in technews_header1 and technews_header2 portal modes.
I've fixed it for myself by just changing http to https in the if statement. You might want to fix that, so both work out of the box and also check if other portal modes have the same deficiencies :)

**Comment by dziudek** [comment]
Thank you for the feedback - issue is fixed on the repo:

https://github.com/GavickPro/News-Show-Pro-GK5/commit/4de5ffce90f424c191dafa07dd8d22acd1efbd59
https://github.com/GavickPro/News-Show-Pro-GK5/commit/e3b96b768dc0339072ef0bea6b9db48cf18bb240
