### ISSUE TITLE
Fatal error: Class 'VmConfig' not found in 

### ISSUE THREAD

**Issue by Mazinguer04** [GavickPro/News-Show-Pro-GK5#369]
Hi
I have this error:

Fatal error: Class 'VmConfig' not found in /Applications/XAMPP/xamppfiles/htdocs/modoshop/modules/mod_news_pro_gk5/tmpl/portal_modes/product_gallery/controller.phpon line 40

I have read this "Please change button type from cart in the portal mode additional settings tab.”, but in Product_galleryII, isn’t button type…

If i put the mode “product_gallleryII”, so, show the module, but show other error:

Notice: Trying to get property of non-object in /Applications/XAMPP/xamppfiles/htdocs/modoshop/modules/mod_news_pro_gk5/tmpl/portal_modes/product_gallery_2/controller.phpon line 85

If a put the module at diferent menú and different  template, all its ok. 

¿can something help me? i have spend five days try to configure the mod_news_pro_gk5_J!3. Run on joomla 3.6.2 & VM 3.

THANK YOU !

**Comment by dziudek** [comment]
Please try to apply this patch: https://github.com/GavickPro/News-Show-Pro-GK5/commit/848224c171ecf30865063fcd36fa0922a73a07aa

**Comment by Mazinguer04** [comment]
Thanks you. It was a perfect solution.
