### ISSUE TITLE
Keep getting this sql error

### ISSUE THREAD

**Issue by jimijon** [GavickPro/News-Show-Pro-GK5#48]
1064
ERROR: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY content.created DESC' at line 29 SQL=SELECT content.id AS iid, content.access AS access, categories.title AS catname, users.email AS author_email, content.created_by_alias AS author_alias, users.name AS author_username, content_rating.rating_sum AS rating_sum, content_rating.rating_count AS rating_count, CASE WHEN CHAR_LENGTH(content.alias) THEN CONCAT_WS(":", content.id, content.alias) ELSE content.id END as id, CASE WHEN CHAR_LENGTH(categories.alias) THEN CONCAT_WS(":", categories.id, categories.alias) ELSE categories.id END as cid  FROM j3n5_content AS content LEFT JOIN j3n5_categories AS categories ON categories.id = content.catid LEFT JOIN j3n5_users AS users ON users.id = content.created_by LEFT JOIN j3n5_content_rating AS content_rating ON content_rating.content_id = content.id WHERE ORDER BY content.created DESC

**Comment by ANDiTKO** [comment]
Try Basic Settings (under your GKnews module) -> and Load the original.json configuration. Then re-save your module.

That worked for me. I tired all the other things but loading the original config fixed it.
