### ISSUE TITLE
First news number with Title Overlay Issue

### ISSUE THREAD

**Issue by mfmarketing** [GavickPro/News-Show-Pro-GK5#75]
Hi - I'm looking to purchase a subscription and I see in your forums that there is an outstanding issue with the News Show Pro that I wanted to know if it was fixed before I purchase. 

The problem seems to be that when you set the "First news number" field to anything other than 0, more than one article appears (when you set the module mode to Title Overlay). Can you tell me if this is a bug that has been fixed or user error? And if it is user error, what the outcome is?

**Comment by bopomo** [comment]
My News Show Pro GK5 only shows the original 3 articles.  The later added 4 articles are not shown.  Can I send you my access details?
